### PR TITLE
Added aws region mumbai: ap-south-1

### LINKED ISSUE #1952: AWS region ap-south-1 missing from 2.5-branch
Was added to in commit acae5dcf but has not been cherry-picked to release-2.5-branch.

### PR DESCRIPTION
**Pull request by stelund**
Signed-off-by: Stefan Lundström stelund@gmail.com

closes #1952

### CODE REVIEW

**Comment by aaronlehmann** [comment]
When you update vendored code, please use the `godep` tool so that the `Godeps.json` file is kept in sync.

Also, I'm not sure `release/2.5` is the correct branch to open the PR against. Generally PRs are opened against master.

**Comment by stelund** [comment]
@aaronlehmann It's already fixed in master. I pointed to the commit in the issue, acae5dc. But it's a big change so I doubt you want to include it in 2.5 release branch.

**Comment by aaronlehmann** [comment]
Thanks, I didn't notice this.

I suspect that we'd rather cherry-pick the whole change, but I'll let the other maintainers comment on this.

**Comment by RichardScothern** [comment]
@stelund the release candidate for 2.5 has already been made.  I'm only considering bug fixes for minor releases.  This feature will be available in 2.6

**Comment by stelund** [comment]
Aw ;( I'm sad Amazon didn't just make an text field for it.

**Comment by stelund** [comment]
@RichardScothern it looks like it didnt make it to 2.6 either

**Comment by ankitforcode** [comment]
@stelund you could use it from the below repo till the time ap-south-1 makes to release 

https://hub.docker.com/r/ankitforcode/registry/

**Pull request closed without merging**
