### PR TITLE
Adds new StorageDriver.FileWriter interface

### PR DESCRIPTION
**Pull request by BrianBland**
Implements new StorageDriver.FileWriter interface as defined in #1395 

Currently works for the following drivers:
+ [x] S3 (aws)
+ [x] S3 (goamz)
+ [x] Filesystem
+ [x] Inmemory
+ [x] Azure
+ [x] Swift
+ [x] GCS
+ [x] OSS

### CODE REVIEW

**Comment by BrianBland** [comment]
@docker/distribution-maintainers I think the changes to registry/storage are ready for review before finishing up with the Swift/GCS/Rados drivers

**Comment by aaronlehmann** [comment]
This is a bit difficult to review in the current state because of the huge vendoring commit. Github can't display the diff because it's too big. I commented on the actual commit earlier, but the comment seems to have been lost after a rebase.

If #1385 is ready to merge, merging it would make things easier here.

**Comment by BrianBland** [comment]
Very understandable. I believe #1385 is ready to go...

**Comment by BrianBland** [comment]
Unfortunately that one isn't easy to review either

**Comment by stevvooe** [comment]
LGTM on the interface changes except for the `Size()` method.

**Comment by BrianBland** [comment]
This is going to be sort of a challenge to merge without temporarily disabling some of the community drivers. I don't have a reasonable test environment for swift, rados, or oss.

@lebauce / @nevermosby could either of you update the swift driver to the new specification and make a PR to my fork?

@gierschv could you help update the rados driver?

@denverdino / @Liuchang0812 could you help with the OSS driver?

**Comment by denverdino** [comment]
@BrianBland , Sure, I will change the OSS driver

**Comment by denverdino** [comment]
@BrianBland , the PR of [Support FileWriter interface for OSS storage driver](https://github.com/BrianBland/distribution/pull/2) is submitted.

**Comment by Liuchang0812** [comment]
@all 

Does anyone working on Swift/Rados? If no, I'd like to do it.

**Comment by BrianBland** [comment]
@Liuchang0812 no one has committed to updating those drivers yet. Any help would be greatly appreciated :+1:

**Comment by lebauce** [comment]
@Liuchang0812 Hi. I'm working on the Swift driver. Did you start working on it ?

**Comment by Liuchang0812** [comment]
@lebauce thanks, you could do it.

**Comment by BrianBland** [comment]
@Liuchang0812 @lebauce I just updated the Swift driver in the latest commit. Feel free to review the changes

**Comment by BrianBland** [comment]
As part of this refactor, I've decided to remove the rados driver in favor of the updated Swift driver.

Anyone who wishes to use the registry with Ceph as the underlying storage backend should use the Ceph Object Gateway. I've successfully tested this with the Swift driver using a configuration such as:

```yaml
swift:
  authurl: http://192.168.33.10:7480/auth/v1
  username: "testuser:swift"
  password: "mypassword"
  container: testing
```

It's possible that this also works correctly with the S3 driver thanks to #1512, but v4 auth support was only just merged into Ceph as of https://github.com/ceph/ceph/pull/4943 (26 days ago), so it's doubtful that production deployments currently support this, and the stability is as of yet unverified.

**Comment by dmcgowan** [comment]
LGTM on interface and handler changes

**Comment by stevvooe** [comment]
LGTM

@BrianBland I'm not sure what to do on the `rados` driver. I'd prefer to drop support if we don't have a maintainer.

**Comment by RichardScothern** [comment]
@stevvooe with some judicious documentation, I don't think the ceph driver will be missed.  

Any ceph user can put the swift gateway in front of their cluster and use the swift driver (and soon the s3 driver).   In fact, Swift supports the S3 driver, so we could conceivably rid ourselves of that driver too :joy_cat:

**Comment by RichardScothern** [comment]
LGTM.  This is great in a number of ways :clap: :clap: :clap:

**Comment by stevvooe** [comment]
:+1:

**Pull request merged**
