### PR TITLE
Fix relinker

### PR DESCRIPTION
**Pull request by dmp42**

### CODE REVIEW

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers 

See commit message.

**Comment by dmp42** [comment]
FWIW I link-checked every top-level page of the generated documentation and it seems ok to me.
Please say so if I missed one.

**Comment by aaronlehmann** [comment]
LGTM. Didn't find any broken links.

I noticed that the Aliyun OSS doc page has no styling applied, but I'll open a separate issue or PR about this.

**Comment by RichardScothern** [comment]
LGTM

**Comment by thaJeztah** [comment]
@moxiegirl should the same be applied to the other projects as well?

**Comment by dmp42** [comment]
@thaJeztah it should rather be "upstreamed" into the docs base image.
There is really no valid technical reason for duplicating this across projects.

Also, this hasn't been tested with the other projects. If other cases have to be handled, they should be added to the tests.

**Comment by thaJeztah** [comment]
@dmp42 agreed, should probably move this into a script, so that we can pass the `$PROJECT` var during build.

Thanks for the test btw, nice touch!

**Comment by moxiegirl** [comment]
@thaJeztah I'lll test it in other environments I'm moving everything in to a script as I update for building all --- see compose projects.  Thanks for the change @dmp42.

**Pull request merged**
