### PR TITLE
Fix table render in specs/api.md

### PR DESCRIPTION
**Pull request by vdemeester**
There is some problems with table on the api page : https://docs.docker.com/registry/spec/api/#errors-2.

This PR fixes that on the ``api.md`` file only. I can take a *tour* of the other pages if needed.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by stevvooe** [comment]
@vdemeester These tables are autogenerated using `docs/spec/api.md.tmpl`. You'll have to fix it in the template then rebuild with `make docs/spec/api.md`.

**Comment by stevvooe** [comment]
@moxiegirl These tables are rendering correctly in github. We need to flow a bug up to hugo to get this fixed.

**Comment by vdemeester** [comment]
ah right, ok I'll do it tomorrow then.

**Comment by vdemeester** [comment]
@stevvooe Done.

@moxiegirl @stevvooe Hugo uses [blackfriday](https://github.com/russross/blackfriday), and github uses [rdiscount](https://github.com/davidfstr/rdiscount). The bug should probably filled to the blackfriday repository but the question is also : which of rdiscount or blackfriday implements table in Markdown the *right* way, and is there a right way :blush:.

**Comment by moxiegirl** [comment]
@vdemeester Thanks for the fix.  Yes, Blackfriday seems to have the capability of specifying a GFM renderer.  Then, I need to do some work with Hugo to get it to allow me to specify the Markdown I'm going to hand it.  Some discussion here: https://github.com/russross/blackfriday/issues/91 re this topic.

Anyway, thanks for the catch and the contrib. Pulled this PR ran to confirm the fix. LGTM

**Comment by stevvooe** [comment]
@vdemeester Thank you for the fix. LGTM

**Pull request merged**
