### PR TITLE
Changed cmd/registry/main.go resolveConfiguration to read the env REG…

### PR DESCRIPTION
**Pull request by nhalm2**
…ISTRY_CONFIGURATION_PATH before reading the arguments.  With the supplied Dockerfile you can now specify a configuration file without having to rebuild the container.

Signed-off-by: Nick Halm <nick.halm@live.com>

### CODE REVIEW

**Comment by nhalm2** [comment]
I am trying to make it easier to use a whole configuration file.  I was never able to actually redirect the image of a config.yml to the container.  I think this is a good option.  The Dockerfile doesn't need to be changed then, and it will still work as advertised out of the box.  
```
docker run --rm -p 5000:5000 -e REGISTRY_CONFIGURATION_PATH=/root/config.yml -v root/config.yml:/root/config.yml registry-test
```

**Comment by stevvooe** [comment]
This should favor the command line argument over the configuration path. For example, running the following, I would expect `config-arg.yml` to be favored over `config-env.yml`.:

```
REGISTRY_CONFIGURATION_PATH=config-env.yml registry config-arg.yml
```

If the problem is that the Dockerfile is not allowing you to override the configuration, we may need a better approach. Does passing in the path as the first argument not work?

```
docker run --rm -p 5000:5000 -v root/config.yml:/root/config.yml registry-test /root/config.yml
```

As it stands, we are not yet happy with the current official image. We definitely need to make some changes here.

**Comment by stevvooe** [comment]
cc @dmp42

**Comment by nhalm2** [comment]
@stevvooe sorry to waste your time.  I am pretty sure that I tried that but I couldn't get it to work.  After further review ```docker run --rm -p 5000:5000 -v /root/config.yml:/root/config.yml registry:2.0 /root/config.yml``` does work.  Thanks for your help.

**Comment by dmp42** [comment]
Possibly worth adding examples to the doc?

**Comment by stevvooe** [comment]
@nhalm2 No problem. This is never a waste of my time ;). I just wanted to clarify what behavior was expected.

We are interested in making this as easy as possible. Several users are having issues surrounding configuration of the official image (see #385 for details). We may look into a solution similar to what you've suggested here.

@dmp42 Agreed. I believe @moxiegirl is looking to address this in the documentation.

**Pull request closed without merging**
