### PR TITLE
doc: document approach to eventual consistency

### LINKED ISSUE #146: Document approach to dealing with eventual consistency
There are properties of the backend storage layout that are important to maintain to deal with eventually consistent backends. The approach is covered, in part, in https://github.com/docker/distribution/issues/143#issuecomment-72923206.

There should be a section in the architecture portion of the documents that covers these issues. Such knowledge would be useful for contributors as guidelines for modifying the layout as well as operators when troubleshooting problems.

### PR DESCRIPTION
**Pull request by stevvooe**
There is probably a better place for this documentation but we'd like to move
this elsewhere than a github issue. We can move this to a more appropriate
location with the documentation effort.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

Closes #146

cc @moxiegirl

### CODE REVIEW

**Comment by moxiegirl** [comment]
@stevvooe Understood.  If you want to merge this I'll sort it out.

**Comment by dmp42** [comment]
LGTM

**Comment by ahmetalpbalkan** [comment]
you rock :metal:

**Comment by dmp42** [comment]
@stevvooe at the office, picture shot last week :)

image

**Pull request merged**
