### PR TITLE
Bump to go1.7

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Ref: #2028

@dmcgowan let's see how this goes.

### CODE REVIEW

**Comment by ahmetalpbalkan** [comment]
This fails with go vet error:

```
Now using version stable
+ vet
registry/storage/driver/swift/swift.go:213: literal copies lock value from ct: github.com/docker/distribution/vendor/github.com/ncw/swift.Connection contains sync.Mutex
registry/storage/driver/swift/swift.go:787: literal copies lock value from d.Conn: github.com/docker/distribution/vendor/github.com/ncw/swift.Connection contains sync.Mutex
exit status 1
make: *** [vet] Error 1
```

I assume this check is added to `go vet` recently with go1.7. Should we pull in the maintainer of swift driver?

**Comment by RichardScothern** [comment]
It will probably be quicker to fix this ourselves.  I'll have a look today.

**Comment by ahmetalpbalkan** [comment]
@RichardScothern I can take this up.

**Comment by RichardScothern** [comment]
thanks @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
@RichardScothern it's green now!

**Comment by RichardScothern** [comment]
excellent.  Were you able to test it at all?

**Comment by ahmetalpbalkan** [comment]
@RichardScothern I've been building the source on go1.7.1 myself for the past month or so. It seems to be working.

**Comment by RichardScothern** [comment]
@ahmetalpbalkan that comment was meant for the other PR, mea culpe

**Comment by ahmetalpbalkan** [comment]
Oh the swift driver PR? Nope, I have not tested it.

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
