### PR TITLE
Fix the sentence

### PR DESCRIPTION
**Pull request by stepyu**
Signed-off-by: Jie Yu <390282283@qq.com>

### CODE REVIEW

**Comment by dmcgowan** [comment]
We require commit signing even for small commits like this

**Comment by stevvooe** [comment]
@stepyu Please sign the commit.

**Comment by stepyu** [comment]
Signed-off-by: Jie Yu <390282283@qq.com>

**Comment by stepyu** [comment]
@stevvooe @dmcgowan 
can above comment works?

**Comment by stevvooe** [comment]
@stepyu No, you need to sign the commit. Follow the instructions in https://github.com/docker/distribution/pull/2328#issuecomment-313812219.

**Pull request merged**
