### PR TITLE
Send manifest and blob delete events to the notifications subsystem.

### LINKED ISSUE #1396: DELETE an image registry does not send out an event/notification
Per my testing and per the doc:
https://docs.docker.com/registry/notifications/

Seems when a DELETE http request is triggered there won't be any events sent out from registry.  

Is there plan to support that?

### PR DESCRIPTION
**Pull request by RichardScothern**
Send manifest and blob delete events to the notifications subsystem.

Closes #1396 
Signed-off-by: Richard Scothern <richard.scothern@gmail.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by BrianBland** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by RichardScothern** [comment]
@stevvooe @BrianBland : currently this PR sends the same `target` struct for manifest and blob deletes (digest, repo).  I'm considering adding an identifier field ('manifest' or 'blob') to allow consumers to differentiate the event type.  Does this sound reasonable?

**Comment by stevvooe** [comment]
>  currently this PR sends the same target struct for manifest and blob deletes (digest, repo). I'm considering adding an identifier field ('manifest' or 'blob') to allow consumers to differentiate the event type. Does this sound reasonable?

This should be in the mediaType field. Just noticed that these are omitted by the documentation.

**Pull request merged**
