### PR TITLE
Fix some typos in comments and strings

### PR DESCRIPTION
**Pull request by stweil**
All of them were found and fixed by codespell.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by stweil** [comment]
The statistics about code coverage looks strange. Why can a typo fix decrease code coverage?

**Comment by BrianBland** [comment]
@stweil No need to worry about this. The cloud storage driver tests do not run in CircleCI on PRs, so we end up with a displayed drop in coverage on each PR. 

I appreciate the typo fixes, but could you please not change the files included within `Godeps/_workspace/`? These are vendored directly from other repositories, so if anything we should make pull requests to clean up these dependencies at the source. Admittedly that sounds like it could be a daunting process...

**Comment by stweil** [comment]
Updated pull request, now without `Godeps/_workspace`.

**Comment by RichardScothern** [comment]
LGTM :+1:

**Comment by BrianBland** [comment]
:+1:

**Pull request merged**
