### PR TITLE
Bump golang to v1.14.1

### PR DESCRIPTION
**Pull request by chenrui333**
Bump golang to the latest version, v1.14.1 as in go v1.14 it has better vendor support.

### CODE REVIEW

**Comment by olegburov** [comment]
@manishtomar @dmcgowan @thaJeztah can you please close this PR in favor of https://github.com/docker/distribution/pull/3222?

**Comment by chenrui333** [comment]
I can close this one, thanks @olegburov!

**Comment by olegburov** [comment]
Thanks, @chenrui333.

**Comment by chenrui333** [comment]
no worries.

**Pull request closed without merging**
