### PR TITLE
docs: fix registry link to point to localhost in deploy doc

### PR DESCRIPTION
**Pull request by nubs**

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @moxiegirl

**Comment by moxiegirl** [comment]
nice catch @nubs LGTM

**Comment by stevvooe** [comment]
@nubs Thank you for the contribution! Could you please sign the commit?

**Comment by nubs** [comment]
Signed, thanks!  The contributing docs for docker/distribution don't mention signing commits so I also created #377 to track that.

**Comment by stevvooe** [comment]
@nubs Thank you for the addition!

**Pull request merged**
