### PR TITLE
Updated to aws-sdk-go v1.23.7 release - to support newer endpoints li…

### PR DESCRIPTION
**Pull request by KlavsKlavsen**
…ke eu-north-1

This resolves issue https://github.com/docker/distribution/issues/2870
I verified by building and running locally with my config using eu-north-1 - and it works :)
I'm hoping there is a CI pipeline here that runs tests and verifies "everything else still works" :)

### CODE REVIEW

**Comment by KlavsKlavsen** [comment]
I took the liberty of also doing -S - so its gpg signed as well - using my yubikey :)

**Comment by KlavsKlavsen** [comment]
It seems the pipeline does a diff - and since updating the aws is a big diff.. the job ends with:
"The job exceeded the maximum log length, and has been terminated."

But is anything wrong with my commit?

**Comment by olegburov** [comment]
@dmcgowan @manishtomar @thaJeztah can you please close this PR because AWS SDK has been already upgraded to latest `1.34.x` in https://github.com/docker/distribution/pull/3118?

**Comment by manishtomar** [comment]
Thanks @olegburov for the reminder. Closing as per above comment.

**Pull request closed without merging**
