### PR TITLE
Move 'Recipes' into the Registry menu

### LINKED ISSUE #1336: Missing documentation for setting up Registry Mirror
The first result of a [Google search for "docker registry mirror"](http://www.google.com/search?q=docker%20registry%20mirror) is https://docs.docker.com/engine/articles/registry_mirror/, where we find the following content:

> ### Run a local registry mirror
The original content was deprecated. An archived version is available in the 1.7 documentation. For information about configuring mirrors with the latest Docker Registry version, please file a support request with the Distribution project.

Consider this said support request.

Is there any documentation for this? If so, I'm unable to find it, and it should be linked from the aforementioned page.

In my particular case, I have a GitLab CI runner which tries to pull helper images as part of its build. However, this runner does not have access to the internet, so I'm trying to figure out the best way to set up my Docker daemon, or private registry, or both, in order to provide these images. (https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/980)

### PR DESCRIPTION
**Pull request by RichardScothern**
Closes #1336 

preview

Signed-off-by: Richard Scothern <richard.scothern@gmail.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
@moxiegirl : is it possible to move this to the bottom of this section.  Also, can you confirm the 'snm_' prefix is not unexpected.

**Comment by dmp42** [comment]
@RichardScothern can you try using "weight"?

See https://raw.githubusercontent.com/docker/distribution/master/docs/configuration.md

**Comment by RichardScothern** [comment]
done.  @moxiegirl : could you cast an expert eye over this please?

**Comment by moxiegirl** [comment]
LGTM

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
