### PR TITLE
Allow skipping name verification

### PR DESCRIPTION
**Pull request by tt**
This implements an option to skip name verification which will allow rewriting names. See #1057 for more details.

### CODE REVIEW

**Comment by tt** [comment]
@stevvooe, can you review this?

(The failures look irrelevant; I see failed builds for master too.)

**Comment by stevvooe** [comment]
@tt The code looks okay. However, I am not sure if we can support any registry that returns an image from a repository with a different name. The data model just doesn't work like that. Relaxing this requirement may be okay, but due diligence must be done to ensure that guarantee isn't relied upon.

We are changing the [manifest format](https://github.com/docker/distribution/pull/1068) to not have the name, which is arguably the correct design. Repository rename will be less of an issue. 

@RichardScothern @dmcgowan Are there places in the client and notary that we need to update for this to work correctly?

**Comment by tt** [comment]
I'm actually less concerned with the client supporting this and more with not persisting names on disk making it harder to support it later without renaming all files.

I'll take a look at the manifest format proposal but I'd appreciate if you can still consider merging this in the interim.

**Comment by stevvooe** [comment]
@tt It absolutely matters if the clients validate this, as a registry that has enabled this option would be completely useless. Manifests served with the incorrect name would be rejected. I don't think we can do this without the due diligence.

**Comment by tt** [comment]
@stevvooe, the point is that my mapping is internal; it's still served from the original name.

**Comment by stevvooe** [comment]
@tt That is the problem. The puller says fetch `foo/bar` and the a manifest comes back with the name `bar/baz`, since the backend repository `bar/baz` was renamed to `foo/bar`. If the client expects that the `name` field of the manifest matches the thing they ask for, which is a reasonable expectation, it will reject it.

**Comment by tt** [comment]
It has less to do with allowing user-facing renames (for now) and more about choosing a storage strategy that will support it when the manifest changes.

That said, I think it would be possible to allow renames by also patching the manifest when a rename happens.

**Comment by dmcgowan** [comment]
I can confirm that the Docker client version 1.6 - 1.9 do not check the manifest name and there are no plans to. We did not check the manifest name since we were intent on deprecating the name field in the manifest pre-1.6.

**Comment by stevvooe** [comment]
@tt Due to content addressability, the name cannot be rewritten at request time, unless the manifest is requested by tag.

@dmcgowan In your opinion, could we just remove the name check altogether?

**Comment by dmcgowan** [comment]
@stevvooe I don't think the name check is in use. My only concern would be by removing it we are opening up possible use cases we have no interest in supporting for the current manifest schema version.  Aside from this concern, removing altogether is favorable than making it configurable. So yes, we should just remove altogether.

**Comment by stevvooe** [comment]
Okay, let's get some quorum going here.

@RichardScothern @aaronlehmann @jlhawn @dmp42

Are we okay with allowing manifests to have different names than their repositories?

**Comment by aaronlehmann** [comment]
Will this have an impact on notification hooks? I may be misremembering, but I thought the names in notifications came from the manifest. If so, some notification consumers may assume this is actually the repository's name.

**Comment by stevvooe** [comment]
@aaronlehmann Interesting. Repository name is all set by the repository hooked into the notifications. No issue there.

**Comment by tt** [comment]
Any news?

**Comment by stevvooe** [comment]
@tt We need consensus from @RichardScothern @aaronlehmann @jlhawn @dmp42 @endophage

**Comment by jlhawn** [comment]
oh, sorry. LGTM

The name really should have never been in the manifest anyway.

**Comment by aaronlehmann** [comment]
LGTM

**Comment by dmp42** [comment]
Circle and Janky don't seem to agree :-)

@RichardScothern are you comfortable with this change?

**Comment by tt** [comment]
@dmp42, the CircleCI failure looks like misconfiguration of the S3 driver. I don't think that's related to this pull request.

@stevvooe, based on the feedback, should this really be an option or should I open another pull request that removes the check entirely?

**Comment by RichardScothern** [comment]
I've restarted the build

**Comment by stevvooe** [comment]
@tt We are leaning towards removing the check entirely.

**Comment by aaronlehmann** [comment]
I support removing the check.

**Comment by RichardScothern** [comment]
+1

**Comment by stevvooe** [comment]
@tt Go ahead and update that PR. Sounds like we have solid consensus here.

Sorry for all the flip flopping on this one. This is a very sensitive piece of code. We are glad to have your contributions!

**Comment by tt** [comment]
I'm closing this; #1211 is where the magic happens.

**Pull request closed without merging**
