### PR TITLE
Remove the unimplemented monolithic upload section from the API

### PR DESCRIPTION
**Pull request by RichardScothern**
Signed-off-by: Richard Scothern <richard.scothern@docker.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
To be reinstated with #1170 (or equivalent)

**Comment by aaronlehmann** [comment]
Reluctant LGTM

**Comment by SvenDowideit** [comment]
LGTM on the presumption that this doc is premature to the implementation?

**Comment by stevvooe** [comment]
This should have been left in as part of the specification, even if it is unimplemented. The documentation provides guidelines for implementation.

If we need a separate API usage guide, we should do that. However, this is specification and should be treated as such.

**Comment by cliffbdf** [comment]
Problem is, people outside docker are writing apps based on the spec. Perhaps each spec needs a major version number (e.g., 2.2) so that it matches the actual implementation of that version of the registry? That way, a future version (e.g., 2.5) could have a spec 2.5 and future functionality plans could go into that?

**Comment by stevvooe** [comment]
@cliffbdf https://github.com/docker/distribution/blob/master/docs/spec/api.md#changes has the versioning. Either way, the specification should not be used as an implementation guide. There needs to be a separate documentation indicating implementation status.

It is unfortunate that this change came without an update to the change log.

I really think this should be reverted.

**Comment by cliffbdf** [comment]
A separate document indicating implementation status would work for me. (I am a user of the registry, writing code that accesses the registry via its API.) I suggest that if a separate implementation status doc is created, that the v2 spec mention that doc's location at the beginning of the v2 spec, so that one can easily find the implementation status.

**Comment by cliffbdf** [comment]
So I now compute the digest manually - it does not match the directory name that contains the layer. But no problem. But I discovered that the digest must have the SHA format prepended to it - in this case, "sha256: ". I know that is in the docs somewhere, where digests are discussed, but it might be good to add it to the v2 spec since merely stating that the digest should be provided as a query string is probably not sufficient to inform people that the digest must prepend "sha256:". Just a suggestion :-)

**Comment by stevvooe** [comment]
@cliffbdf It is right there: https://github.com/docker/distribution/blob/master/docs/spec/api.md#content-digests. There is also this: https://godoc.org/github.com/docker/distribution/digest.

**Comment by cliffbdf** [comment]
Indeed. Thanks!

**Comment by cliffbdf** [comment]
Indeed, someone in this group was nice enough to point me to some BNF for names: [https://github.com/docker/distribution/blob/master/reference/reference.go#L4](https://github.com/docker/distribution/blob/master/reference/reference.go#L4) I think that users of the API will greatly benefit from that BNF becoming part of the API spec. I had forgot to check it, and having it in the spec would have helped me to discover my digest syntax error (which would have saved Steve from having to point it out - thanks Steve!)

But now I am struggling with the "last mile" of posting an image to v2: I am getting a 400:
`{"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","detail":{}}]}`
But my manifest appears valid, although it is not clear from the spec if the history and signature fields are required. I don't have either - so I hope they are not! I wish that the "detail" part of the message provided some details - would be very helpful ;-)

**Comment by stevvooe** [comment]
@cliffbdf I'd really recommend reading the client code. There are a number of comments and tests that will explain to all of these problems without having to have us explain each detail, possibly missing important aspects.

The problem here is that the `signature` field is a part of the manifest specification, which the API does some validation on. You'll have to refer the manifest specification for the specific revision you are interested in.

**Comment by cliffbdf** [comment]
Ah, yes, I forgot that there is a separate manifest spec. Thanks Stephen!

**Pull request merged**
