### PR TITLE
api.md:fix disordered placement of section "Deleting a Layer"

### PR DESCRIPTION
**Pull request by TrumanLing**
Signed-off-by: Ling FaKe lingfake@huawei.com

### CODE REVIEW

**Comment by johndmulhausen** [comment]
Hey guys, this PR needs to be moved to the docs repo: https://github.com/docker/docker.github.io/tree/master/registry

**Comment by stevvooe** [comment]
@johndmulhausen This is the API specification. It does not belong in the docs repo. How did they end up there?

@TrumanLing This fix needs to be made in the template.

**Comment by TrumanLing** [comment]
@stevvooe sorry for my late response, where is the template?

**Comment by stevvooe** [comment]
@TrumanLing `docs/spec/api.md.tmpl`, right adjacent to the doc.

**Comment by TrumanLing** [comment]
@stevvooe I have done it with files api.md and api.md.tmpl, PTAL

**Comment by stevvooe** [comment]
LGTM

@johndmulhausen In the future, please avoid deleting comments. It creates confusion and we lose context to the discussion. I've added the quote there to ensure the context isn't lost. It's okay to say something incorrect. :)

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
