### PR TITLE
fix secure_registry image name in docs

### PR DESCRIPTION
**Pull request by Rob-Johnson**
Minor typo fix in docs

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM!

cc @moxiegirl

**Comment by stevvooe** [comment]
@Rob-Johnson Could you please sign your commit?

**Comment by moxiegirl** [comment]
Nice catch, thanks! LGTM

**Comment by stevvooe** [comment]
@Rob-Johnson Merged #389 instead. Thank you!

**Pull request closed without merging**
