### PR TITLE
Fix S3 Delete method's notion of subpaths

### PR DESCRIPTION
**Pull request by nwt**
Deleting "/a" was deleting "/a/b" but also "/ab".

### CODE REVIEW

**Comment by RichardScothern** [comment]
Waiting on #1987 to fix the build

**Comment by nwt** [comment]
@RichardScothern: Want me to rebase now that #1987 has been merged?

**Comment by RichardScothern** [comment]
yes please

**Comment by nwt** [comment]
@RichardScothern: Rebased.

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
