### PR TITLE
Update Golang to 1.10

### PR DESCRIPTION
**Pull request by thaJeztah**
ping @stevvooe @dmcgowan

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

**Comment by thaJeztah** [comment]
Tests keep failing on `x509: certificate has expired or is not yet valid` 😞

**Comment by thaJeztah** [comment]
Ah hm... looking at https://github.com/docker/distribution/blob/11406050aff4a727bd6d3f427d04eac914e22886/contrib/docker-integration/nginx/ssl/registry-ca%2Bca.pem

```
Certificate Information:
Common Name: QuickTLS
Organization: QuickTLS
Valid From: May 26, 2015
Valid To: May 10, 2018
Issuer: QuickTLS, QuickTLS
Serial Number: 32c74f5a82c0b28fed20ebcb93c47fb0
```

**Comment by dmcgowan** [comment]
Opened #2594 to fix tests

**Pull request merged**
