### PR TITLE
[driver/s3] Use aws/aws-sdk-go instead of goamz for s3 driver and cloudfront

### PR DESCRIPTION
**Pull request by BrianBland**
I didn't change any of the s3 driver logic, only the s3 client calls to use this other library.

Caveats: V2 auth not supported, EC2 file credentials untested, cloudfront untested.

Some very unscientific tests show a 45% time reduction for running the s3 driver tests on my local computer as compared to master, and a 40% time reduction as compared to #1381 (connection pooling enabled).

### CODE REVIEW

**Comment by stevvooe** [comment]
@BrianBland Great looking numbers.

Would it be a good idea to adopt this as a separate, experimental driver (say, `aws-s3`) so we don't force people over immediately?

**Comment by dmp42** [comment]
Definitely +1 on not forcing the new code on people.

Either a new, differently named driver, or a flag/config value in the existing driver (`legacyCode: true`) that would toggle it, and that we can default to false in the future.

**Comment by stevvooe** [comment]
> Definitely +1 on not forcing the new code on people.

Not initially. We just don't know how stable this is. Long term, I don't want us to maintain two copies. :smile_cat:

**Comment by dmp42** [comment]
>  Long term, I don't want us to maintain two copies.

Surely not :) - as soon as the "new" one would be stable enough, the other one would instantly become "unmaintained, use as-is".

**Comment by BrianBland** [comment]
After fixing the connection pooling in docker/goamz, the performance wins in this client change are no longer statistically significant in my testing. Whereas this does seem to have a much better v4 auth implementation, I'd rather stick with the known functional s3 client (goamz) over the auto-generated aws-sdk-go for now.

**Comment by BrianBland** [comment]
Updated to keep both s3 drivers, registers new one as "s3" and "s3aws", registers old driver as "s3goamz"

**Comment by aaronlehmann** [comment]
Looks like hundreds of the files being added in this PR are from the corpus of the fuzz test for `go-jmespath`. Is there any sane way to have godeps exclude these test fixtures? If not, maybe this is a good opportunity to switch to native Go 1.5+ vendoring (`vendor` subdir).

**Comment by BrianBland** [comment]
@aaronlehmann In the meantime I'm willing to manually strip out these fixtures, given that godeps ignores `*_test.go` files anyway

**Comment by BrianBland** [comment]
```
Godep does not copy:
files from source repositories that are not tracked in version control.
*_test.go files.
testdata directories.
```

Maybe we can make a PR to `go-jmespath` to move the test data into a `testdata` directory?

**Comment by BrianBland** [comment]
@aaronlehmann vendoring fix upstreamed through go-jmespath -> aws-sdk-go via aws/aws-sdk-go#538

**Comment by aaronlehmann** [comment]
Nice, that was fast.

**Comment by BrianBland** [comment]
Yeah, this really helps boost confidence in using this library instead of goamz

**Comment by RichardScothern** [comment]
rebase please :credit_card:

**Comment by BrianBland** [comment]
Rebased

**Comment by RichardScothern** [comment]
This will need another rebase to pick up the build fix.  :crying_cat_face:

**Comment by BrianBland** [comment]
Added support for custom UA strings, storage classes (reduced redundancy)

**Comment by RichardScothern** [comment]
LGTM

This PR also uses `aws-sdk-go` for cloudfront URL generation for which we don't test.   It might be a good idea to have a fallback somehow or verify the URLs are the same as before.  I'll leave that up to you.

**Comment by BrianBland** [comment]
Good call, still working on testing the cloudfront signer now

**Comment by BrianBland** [comment]
@RichardScothern confirmed cloudfront middleware is working, also added a bit of extra code for handling incomplete "baseurl" fields (adding the scheme and trailing slash)

**Comment by dmcgowan** [comment]
registry/storage/driver/s3-aws/s3.go:4
> // This package leverages the AdRoll/goamz client library for interfacing with
> // s3.

**Comment by dmcgowan** [comment]
LGTM after comment fix

**Comment by BrianBland** [comment]
@dmcgowan updated package comments for both S3 drivers

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
