### PR TITLE
README, doc: update README and outline documentation

### LINKED ISSUE #209: update distribution project readme
The current readme provides an overview of the open sprint. This needs be update to include common readme items for running and using the registry.

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

Closes #209.

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @dmp42

**Comment by thaJeztah** [comment]
Thanks! Much clearer :)

Do you want to keep the todos in there? Perhaps those should be created as tickets here instead?

**Comment by dmp42** [comment]
LGTM

**Comment by ncdc** [comment]
LGTM

**Comment by bfirsh** [comment]
Great stuff. Agreed the TODOs should be removed and should be issues.

**Comment by stevvooe** [comment]
@bfirsh You're welcome to help in the effort. Please find a way to link missing sections with issues. As a documentation reader, its important to know when a section is incomplete.

**Pull request merged**
