### PR TITLE
Bump aws sdk to v1.15.11

### LINKED ISSUE #2579: Please update registry image (aws-sdk-go outdated - issue with ceph)
I tried to use the registry:2 image with ceph (private s3) but requests are not working.

It succeed when I used a ubuntu image with the latest version of aws-sdk-go and go.

Is it possible to update the registry image with the latest version of go and aws-sdk-go ?

Thanks !

### PR DESCRIPTION
**Pull request by caervs**
This is the latest official release for this dependency

Closes #2579

Signed-off-by: Ryan Abrams <rdabrams@gmail.com>

### CODE REVIEW

**Comment by manishtomar** [comment]
Can you please check why travis fails?

**Comment by dmp42** [comment]
@manishtomar @caervs `script/validate/vendor` is failing

**Comment by caervs** [comment]
Yup. Probably a difference between my version of `vndr` and `travis`'s

**Comment by dmp42** [comment]
This should fix #2579 
This is superseding #2563 and part of #2627

**Comment by caervs** [comment]
> This should fix #2579
> This is superseding #2563 and part of #2627

@dmp42 updating description to reflect that.

**Comment by manishtomar** [comment]
> Yup. Probably a difference between my version of vndr and travis's

Can you please fix this? Would really like to see this succeed with a big vendor update.

**Comment by dmcgowan** [comment]
@caervs this is not your fault, looks like a bad PR got merged into master

**Comment by dmcgowan** [comment]
LGTM

**Comment by danielezer** [comment]
When will this be released as a docker image? @dmcgowan 
I looked at the 2.6.2 version and saw that the latest update was five week ago

**Pull request merged**
