### PR TITLE
Backoff retry on verification to give s3 time to propagate

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
The comment (not visible in the diff) is now out of date (retry is no longer 100ms each time).

**Comment by dmp42** [comment]
LGTM

**Comment by stevvooe** [comment]
@RichardScothern Updated comment.

**Comment by RichardScothern** [comment]
Lovely jubbely.  Ship it!

**Pull request merged**
