### PR TITLE
Upgrade Gorilla Mux to `1.8.0`.

### PR DESCRIPTION
**Pull request by olegburov**
This PR upgrades [Gorilla Mux](https://github.com/gorilla/mux) from `1.7.2` to `1.8.0`.

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Can you squash the commits? Looks like these should all be in a single commit

**Comment by olegburov** [comment]
@thaJeztah done.

**Comment by olegburov** [comment]
Here is a related PR https://github.com/docker/distribution/pull/3242.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@manishtomar @stevvooe PTAL

**Pull request merged**
