### PR TITLE
docs: document running Registry natively on OS X

### PR DESCRIPTION
**Pull request by kelseyhightower**

### CODE REVIEW

**Comment by dmp42** [comment]
Nice!

ping @moxiegirl

**Comment by thaJeztah** [comment]
Oh, thanks! Would be nice if the OS X build was part of the official releases. The accompanying files could possibly be put in a `contrib` directory.

I realise that's not *directly* related to this PR, but just saying 😋

**Comment by kelseyhightower** [comment]
@thaJeztah Happy to have things moved around have the merge.

**Comment by thaJeztah** [comment]
@kelseyhightower sure, it shouldn't hold up this PR (which is great), but hoping this will be simplified in future. Thanks again, really appreciated!

**Comment by moxiegirl** [comment]
LGTM

@thaJeztah I'm anticipating moving it to `contrib` but @kelseyhightower is doing this by request --- I'll shift things after.  I want to talk to the team about how to handle the `contrib` area.

ping @stevvooe @dmp42 for approval an merge

**Comment by dmp42** [comment]
LGTM

Pending @stevvooe opinion before merge.

**Comment by stevvooe** [comment]
The way we have our docs setup, this probably belongs in contrib. Albeit, I don't like having documentation strewn about.

@kelseyhightower If you don't mind, please move this into contrib. If you don't have time, we'll merge and I'll just move it to the right spot.

**Comment by moxiegirl** [comment]
ping @stevvooe if you merge it, I'll carry the change.  Thanks!

**Comment by stevvooe** [comment]
@moxiegirl Could you please move these in another PR?

**Pull request merged**
