### PR TITLE
Fixes so that nginx will start

### PR DESCRIPTION
**Pull request by Boran**
to replace PR #1054
Signed-off-by: Sean Boran <Sean@boran.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
@Boran Looks like you might need to update your local branch. Don't worry about making a second PR: you can just force push to get the changes.

Let me know if you need help doing that.

Sorry for the back and forth here. We really do appreciate the contribution.

**Comment by Boran** [comment]
I started down the rebase rabbit hole, but have hit issues ... stopping for now, too much effort has gone into this over the last three months: just changes a few lines in a doc text file.

**Comment by RichardScothern** [comment]
Carried.

**Comment by 18601673727** [comment]
@Boran After a clean installation on Ubuntu 14.04LTS, tried 
```
docker login -p=testuser -u=testpassword -e=root@example.ch myregistrydomain.com:5043
```
on server turn out success, but at local with same command error occurs:
```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
so tried
```
telnet https://myregistrydomain.com 5043
```
result is `Connected to https://myregistrydomain.`.

So I think there's something wrong still.

**Comment by Boran** [comment]
This fix only solved some initial obvious issues in the documented, but it had not worked for me then either (but that was 3 months ago)

**Pull request closed without merging**
