### PR TITLE
support tag delete via http request 

### PR DESCRIPTION
**Pull request by ChenLingPeng**
like 'curl -v -X "DELETE" http://<your private registry>/v2/library/helloworld/tag/v1'
it will delete tag library/helloworld:v1

### CODE REVIEW

**Comment by ChenLingPeng** [comment]
It's my first PR here, could someone tell what should I do?
qq 20150827152031

**Comment by noxiouz** [comment]
@ChenLingPeng gofmt chekcs that a code format fits to the code style. 
Please, run the ```gofmt -d -s . | grep -v Godeps/_workspace/src/``` inside your fork to look at the diff, which fixes the style. And ```gofmt -s -w . | grep -v Godeps/_workspace/src/``` to apply this fix to your code.

**Comment by ChenLingPeng** [comment]
Thanks @noxiouz . Now it works!

**Comment by stevvooe** [comment]
From the [specification](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-an-image):

> For deletes, reference must be a digest or the delete will fail.

Because manifests have embedded the name and tag, deletions can only be done at the manifest level and only by digest. This is because, under concurrent load, the correct manifest to delete cannot be ascertained with certainty. The correct solution is to separate the tag from the manifest.

Please see https://github.com/docker/distribution/pull/173 for a more complete proposal that would make tag deletion possible.

**Comment by stevvooe** [comment]
I don't feel this is the right approach to the API modifications. I'm closing this until we can get a proper proposal. Please use #174 and commentary from #62 as a template for how this should work.

**Pull request closed without merging**
