### PR TITLE
Re-enable race detector in circleci

### PR DESCRIPTION
**Pull request by dmcgowan**
With go 1.6, concurrent read/write map access can cause a panic, we need the race detector to help prevent against this condition arising.

### CODE REVIEW

**Comment by RichardScothern** [comment]
```
Your build has exceeded the memory limit of 4G on 1 container. ...
```

We should disable for the storage driver tests.

**Comment by RichardScothern** [comment]
LGTM on halt. 🎈

**Comment by dmcgowan** [comment]
The race detector ran! It found 5 races though, so I think I should probably fix those in this PR before merging and break everyone else

**Comment by dmcgowan** [comment]
Finally green, but changes made a few different places and just decided to disable race tests for `registry/handlers` altogether until all the leaks are plugged or it can run quick enough to not hit a timeout.

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
