### PR TITLE
Swift auth version param

### LINKED ISSUE #1044: Add AuthVersion to registry storage driver swift
Registry only maps partial swift connection parameters to config.yml, lacking parameter like AuthVersion. It's hard to use swift service with custom url.

### PR DESCRIPTION
**Pull request by luckyraul**
Closes #1044

### CODE REVIEW

**Comment by RichardScothern** [comment]
@nevermosby : can you opine?

**Comment by RichardScothern** [comment]
ping @lebauce @majewsky for some swift knowledge

**Comment by majewsky** [comment]
Looks good to me. I would clarify the documentation to indicate that the autodetection looks at the auth URL only (see `auth.go` in `ncw/swift`).

**Comment by RichardScothern** [comment]
thanks for this @luckyraul .  Could you address @majewsky's suggestion then we will be good to merge 😸

**Comment by luckyraul** [comment]
@RichardScothern updated

**Comment by RichardScothern** [comment]
LGTM

**Comment by RichardScothern** [comment]
@SvenDowideit is that docs build failure valid?  It doesn't match what is in this PR

**Comment by SvenDowideit** [comment]
yup, ignore the checker, I think we fixed that elsewhere.

**Comment by SvenDowideit** [comment]
retest this please

**Pull request merged**
