### PR TITLE
reference: ParseNamed updated to enforce canonical format

### PR DESCRIPTION
**Pull request by dmcgowan**
Updates the `ParseNamed` function to require that the input be in canonical form. Throws an error if the input is not canonical. This protects against using `ParseNamed` to create partial `Named` values. These partial values can still be created explicitly through `WithName` and `Parse`, as used now used by the registry server.

In the future, the registry should start using fully canonical values on the backend and `WithName` should no longer support creating partial values.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by aaronlehmann** [comment]
Needs a rebase.

**Comment by dmcgowan** [comment]
Rebased and tests passing, this change should get a review from @stevvooe though

**Comment by stevvooe** [comment]
@dmcgowan Should `WithName` not be a combinator?

**Comment by dmcgowan** [comment]
@stevvooe wdyt? Not returning an error so it could be combined with other methods `WithTag(WithName("repo"), "tag")`?

**Comment by stevvooe** [comment]
@dmcgowan That's not exactly what I mean. Usually, `WithXXX` takes an existing things and modifies. In this case, it is creating the first thing.

**Comment by dmcgowan** [comment]
@stevvooe understood. I would like to see `WithName` go away because it doesn't have a good fit with the other functions and "nothing with a name" ends up being a named is not straight forward. We only need this function right now as mechanism for the registry to be able to create a raw named value without normalization. Since the goal of this effort is not just to unify the downstream fork, but as to disambiguate how the package is used, it seems appropriate to rename the function. Some possible names or themes of how it could be replaced are `CreateRawNamed`, `CreateUnnormalizedNamed`. I would want to avoid "ToNamed" or something that signifies transferring a raw string to a named because it may get unintentionally used where a fully normalized name is. What I want to do in the long term is update the registry to just use a fully normalized named. I think given where we want to go, `CreateNamed(domain, path string) (Named, error)` could be the best fit, it would be hard to misuse and the registry could explicitly pass in the domain as `""`.

**Comment by stevvooe** [comment]
@dmcgowan This package seems like it is experiencing some serious bloat. I am not sure if I have the full context to add anything here, but `CreateUnnormalizedNamed` is a mouthful.

LGTM

**Pull request merged**
