### PR TITLE
registry/storage: parallelize signature fetch in signature store

### PR DESCRIPTION
**Pull request by stevvooe**
To avoid compounded round trips leading to slow retrieval of manifests with a
large number of signatures, the fetch of signatures has been parallelized. This
simply spawns a goroutine for each path, coordinated with a sync.WaitGroup.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @jlhawn

**Comment by stevvooe** [comment]
After some testing with s3, I am not sure that this is our performance bottleneck. I'm going to do some more investigating but I think this is related to the fact that each request to s3 creates a connection, due to goamz.

We can merge this PR, anyways, but the performance issue is elsewhere.

**Comment by RichardScothern** [comment]
Some AWS client use the 100 Continue header for S3, which is good for big
object, but doubles the roundtrips - it could be that?

Change lgtm.

**Comment by RichardScothern** [comment]
Actually, 100 continue is just for PUT.  Ignore me.

**Comment by dmp42** [comment]
LGTM

**Comment by stevvooe** [comment]
@RichardScothern Check out https://github.com/AdRoll/goamz/issues/354 for details. I'm going to check this in-depth tomorrow and maybe issue a PR to goamz that addresses this.

**Pull request merged**
