### PR TITLE
In testsuites.go, enlarge the size of randomBytes to 128M to fix the …

### PR DESCRIPTION
**Pull request by hopkings2008**
…crash of running TestConcurrentStreamReads

Signed-off-by: yuzou <zouyu7@huawei.com>

### CODE REVIEW

**Comment by hopkings2008** [comment]
Dear maintainers, 
Please review this change, this will fix the crash of running TestConcurrentStreamReads in storagedriver's testsuites.

**Comment by RichardScothern** [comment]
@hopkings2008 : I believe that the array is only read from and that the size should be increased in case of a panic (indicating array out of bounds access).

**Comment by BrianBland** [comment]
Looks like this does fix that test when not run in short mode, but perhaps we should lower the memory usage of that test instead, as I can't even run the full storage driver test suite on my computer reliably now.

**Comment by BrianBland** [comment]
I say we merge this now and address shrinking the resource usage of the tests in a separate issue/PR

**Comment by RichardScothern** [comment]
@BrianBland  got it.  LGTM.

**Comment by hopkings2008** [comment]
@BrianBland And @RichardScothern , thanks for your checking. I will make enhancements according to your suggestions about to lower the memory of the test. I will try to make it soon.

**Pull request merged**
