### PR TITLE
WIP for muxed S3 streaming commands

### PR DESCRIPTION
**Pull request by dalehamel**
s3gof3r provides faster access reading and writing large files to/from S3.

This is my initial WIP which leverages this library, it is NOT SUITABLE to be merged.

I still need to conduct some performance comparisons to see if it provides a worthwhile speedup

### CODE REVIEW

**Comment by stevvooe** [comment]
@dalehamel It is unlikely that we will take on another library besides [aws-sdk-go](https://github.com/aws/aws-sdk-go) without good data on why another implementation is better. I don't want to get into the same situation as we are with goamz.

**Comment by dalehamel** [comment]
I agree with that, I'll need to do some bench marking to see if the concurrent access to S3 actually provides significantly faster reads/writes for large files.

My current feeling is that even if it does, it's probably not worth the complexity.

**Comment by stevvooe** [comment]
@dalehamel I am going to close this PR. We can carry on the discussion in #433. It would be great to get some help around this area.

**Comment by dalehamel** [comment]
Agreed good to close

**Pull request closed without merging**
