### PR TITLE
adds validation testing for schema version values

### PR DESCRIPTION
**Pull request by mikebrow**
Addresses issue #2650

Signed-off-by: Mike Brown <brownwm@us.ibm.com>

### CODE REVIEW

**Comment by dmcgowan** [comment]
Can you please rebase this to pick up the Travis CI change?

**Comment by mikebrow** [comment]
rebased..

**Comment by dmcgowan** [comment]
LGTM

**Comment by dmp42** [comment]
Thanks @mikebrow !

**Pull request merged**
