### PR TITLE
GCS Storagedriver: fix test failure caused by #1187

### PR DESCRIPTION
**Pull request by aibaars**
This PR fixes a test failure due to an added test case. 

@stevvooe @RichardScothern

### CODE REVIEW

**Comment by RichardScothern** [comment]
Is this necessary?  Unless I'm mistaken, GCS tests have not been failing since #1187

**Comment by aibaars** [comment]
@RichardScothern That is because most of the test suite is not running due to missing Google Cloud Storage credentials ;-)

You would need to  set environment variables: REGISTRY_STORAGE_GCS_BUCKET and (GOOGLE_APPLICATION_CREDENTIALS or REGISTRY_STORAGE_GCS_KEYFILE) to run the GCS tests

**Comment by aibaars** [comment]
@RichardScothern The GCS tests are also quite slow due to use of the rate-limited compose operation. PR #1322 replaces the use of compose with proper resumable uploads.

**Comment by RichardScothern** [comment]
I see.  I thought I had set this up on our continueous build machine, but a quick check reveals not.

LGTM

**Pull request merged**
