### PR TITLE
correct url writing

### PR DESCRIPTION
**Pull request by xiekeyang**
older url writing is failed to  jump correct web.

### CODE REVIEW

**Comment by dmp42** [comment]
LGTM
Thanks for this.

**Comment by stevvooe** [comment]
@xiekeyang This PR should have modified doc/spec/api.md.tmpl, as well. Please submit a PR with the fixed template file.

**Comment by xiekeyang** [comment]
@stevvooe Thanks! I will submit ASAP.

**Comment by stevvooe** [comment]
@xiekeyang Since this has already been merged, you'll need to submit a separate PR.

**Comment by xiekeyang** [comment]
@stevvooe  will do!

**Pull request merged**
