### PR TITLE
Remove dist tool from distribution

### PR DESCRIPTION
**Pull request by stevvooe**
We are headed in a different direction. The dist tool analog will not be a part
of this repository.

cc @icecrime :cry: 

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Don't know if we really care, but `docs/building.md` still references `bin/dist` in an example build log.

**Comment by stevvooe** [comment]
@aaronlehmann Removed.

**Comment by icecrime** [comment]
cry

**Comment by stevvooe** [comment]
@icecrime I'll take that as an LGTM.

**Comment by dmp42** [comment]
@stevvooe https://github.com/stevvooe/distribution/blob/remove-dist-tool/Makefile#L65

**Comment by RichardScothern** [comment]
Farewell, sweet prince :wave:

**Pull request merged**
