### PR TITLE
Ensure read after write for segments

### PR DESCRIPTION
**Pull request by lebauce**
When a manifest has been uploaded, some segments of this manifest may not appear in the object listing yet. The manifest would then report a wrong size. To avoid this, we check that a segment appears after it has been created.

Signed-off-by: Sylvain Baubeau <sbaubeau@redhat.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
@lebauce : do you have an intuition for the time of the database to become consistent?  I wonder if an exponential backoff (with jitter) would work better here?

**Comment by RichardScothern** [comment]
@lebauce : the tests are failing 
`Timeout expired while waiting for segments of /c.ddr2qsa-31dez/1-9f7-1d/taxl/z to show up`

**Comment by lebauce** [comment]
@RichardScothern They fail because the test server incorrectly (part of ncw/swift) implement ETags for manifest. I'll fix it.

**Comment by lebauce** [comment]
@RichardScothern Regarding the time for the database to be consistent, I would say 2 to 3 seconds (that's what I observed on Rackspace Cloud Files)

**Comment by RichardScothern** [comment]
LGTM

**Comment by RichardScothern** [comment]
@nevermosby : could you review?  I would like a second pair of eyes on it

**Comment by nevermosby** [comment]
@RichardScothern LGTM. But I'd like to wait for the feedback of #1013.

**Comment by tdooner** [comment]
@nevermosby We've been running this patch for three days now, and results look good! I'll keep this thread updated if I see the problem resurface.

**Comment by RichardScothern** [comment]
I'm going to merge this.  @tdooner : I'll leave #1013 open for now, please update there if you see the problem again

**Comment by tdooner** [comment]
:+1: Thanks a lot for looking into this! You guys rock.

**Comment by rabb1t** [comment]
Hello guys!

How can I change those timeout settings?

Currently I've faced with the problem when using read/write affinity in my openstack/swift multi-region cluster:

    unable to delete layer upload resources: swift: HTTP Error: 503: 503 Internal Server Error

This caused because not all replicas are available for the GET requests straightaway and the proxy-server replyes with 503 error:

    proxy-server: Object DELETE returning 503 for (204, 404, 404, 503) (txn: tx81cbb381d33e4312a57b3-0056d06af7)
    proxy-server: Object DELETE returning 503 for (204, 404, 404, 503) (txn: tx8c288cf0221240b5a9a15-0056d06b70)
    proxy-server: Object DELETE returning 503 for (204, 404, 404, 503) (txn: tx89edc058dde248a0ae64d-0056d06b72)

Usually it takes about 1 or 2 seconds to move all object's replicas to their proper locations inside the cluster.

**Pull request merged**
