### PR TITLE
Fix release branch

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixing the broken release branch.

This is a cherry pick series to fix broken release.  

/cc ping @stevvooe

### CODE REVIEW

**Comment by moxiegirl** [comment]
@stevvooe when this is merged, I have one more step for the fix which is to push it live.

**Comment by stevvooe** [comment]
@moxiegirl Make sure this is rebased to release/2.0.

**Comment by moxiegirl** [comment]
@stevvooe well that was sloppy --- we should have a hook to catch that.  Fixed.

**Comment by moxiegirl** [comment]
Have no idea why it failing. I'll check back from home and publish live if this gets merged.

**Comment by stevvooe** [comment]
@moxiegirl This is due to coveralls. Has nothing to do with the change. I'll restart the build.

**Comment by moxiegirl** [comment]
LGTM

**Comment by moxiegirl** [comment]
ping @stevvooe if you merge this I will publish. :-D

**Pull request merged**
