### PR TITLE
storage/driver/azure: Update vendored Azure SDK

### LINKED ISSUE #620: Azure backed registry heavily leaks memory
Using registry 2.0.1.

I discovered this memory leak after a registry crash that occurred while pushing several images to my private registry: https://gist.github.com/jesper/25231332f99c92393023

After re-starting the registry, I ran "docker stats registry" and observed the memory usage. Each push to the registry slowly increases the memory usage until it finally falls over. Even if the images have not changed, the memory usage still grows on each push attempt.

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
This change refreshes the updated version of Azure SDK for Go 
that has the latest changes. Also addresses the memory leak
problem.

I manually vendored the new SDK (github.com/Azure/azure-sdk-for-go)
and I removed `management/` `core/` packages manually simply because
they're not used here and they have a fork of `net/http` and `crypto/tls`
for a particular reason. It was introducing a 44k SLOC change otherwise...

This also undoes the `include_azure` flag (actually Stephen removed the
driver from imports but forgot to add the build flag apparently, so the
flag wasn't really including azure. :smile: ). This also must be obsolete
now.

Fixes #620, #175.

Signed-off-by: Ahmet Alp Balkan
cc: @dmp42 @stevvooe

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

@ahmetalpbalkan Thanks! Sorry about disabling the driver temporarily.

**Comment by dmp42** [comment]
LGTM.
Thanks @ahmetalpbalkan !

**Comment by ahmetalpbalkan** [comment]
Awesome, thanks for reviewing.

**Comment by BrianBland** [comment]
LGTM

**Comment by BrianBland** [comment]
Could you also update docs/building.md to remove the `include_azure` build tag info?

**Comment by ahmetalpbalkan** [comment]
I already did. :-)

**Comment by stevvooe** [comment]
@BrianBland Could we get an LGTM here?

**Comment by BrianBland** [comment]
I see the change to docs/storage-drivers/azure.md but not docs/building.md. Everything else is good

**Comment by ahmetalpbalkan** [comment]
@BrianBland oh missed that one, sorry. I fixed that now.

**Comment by BrianBland** [comment]
Awesome, thanks for the quick update

**Comment by stevvooe** [comment]
@ahmetalpbalkan Thank you for the good PR!

**Comment by ahmetalpbalkan** [comment]
You're welcome @stevvooe, always a pleasure! :sunglasses:

**Pull request merged**
