### PR TITLE
Update ncw/swift Vendor Package

### PR DESCRIPTION
**Pull request by cquon**
Updating the github.com/ncw/swift package in vendor to v1.0.40

### CODE REVIEW

**Comment by dmp42** [comment]
First travis failure looks unrelated: https://github.com/docker/distribution/pull/2362#issuecomment-417806504

**Comment by dmp42** [comment]
@caervs @davidswu

**Comment by davidswu** [comment]
@cquon please re-base now that master is green again

**Comment by dmcgowan** [comment]
@mlmhl @cquon Can I get an author name for the commit to add to our .mailmap. Thanks!

**Pull request merged**
