### PR TITLE
API to retrieve lists of manifest descriptors

### PR DESCRIPTION
**Pull request by sergeyfd**
API to retrieve manifests lists

Signed-off-by: Serge Dubrouski <sergeyfd@gmail.com>

### CODE REVIEW

**Comment by sergeyfd** [comment]
This is a first and definitely unfinished iteration for implementation of item 3 from #2170. New endpoint `/v2/<name>/manifests/` returns a list of descriptors for all images in the named repository. More tests need to be added as well as support for pagination and changes in the specification. But let's start a discussion on the main design first.

**Comment by sergeyfd** [comment]
@stevvooe Could you take a look?

**Comment by stevvooe** [comment]
@sergeyfd Is there an update to the specification that describes the changes?

**Comment by sergeyfd** [comment]
@stevvooe No, not yet because I am not sure if this is what we really want. The main idea is that it returns list of manifest descriptors when called through `/v2/<name>/manifests/`. Returning json looks somewhat like this:

```
"name": "test/t1",
	"descriptors": [
		{"mediaType":"application/vnd.docker.distribution.manifest.v2+json",
		 "size":2805,
		 digest":"sha256:899bedd554faf1716d36b310199edae72f348abc8d52ac562cb28cc7998d05e1"},
		{"mediaType":"application/vnd.docker.distribution.manifest.v1+prettyjws",
		 "size":3308,
		 "digest":"sha256:86942f70cd992d0d33d6db048444bc7bb98718c0807a615212346ffada92157f"},
		{"mediaType":"application/vnd.docker.distribution.manifest.v2+json",
		 "size":1768,
		 "digest":"sha256:a27bac78eeee243ce14684870190ad46cefa817bdc046c692a5aed029b5aebf1"}	
	]
```

**Comment by sergeyfd** [comment]
I updated specifications. @stevvooe is there a time line for 2.7 release?

**Comment by dmcgowan** [comment]
Additions to specifications are no longer being considered here. The specification has moved to https://github.com/opencontainers/distribution-spec

**Pull request closed without merging**
