### PR TITLE
Update deploying.md

### PR DESCRIPTION
**Pull request by DreadPirateShawn**
Fixed TLS example to make steps 1 and 2 refer to the same image (secure_registry).

### CODE REVIEW

**Comment by stevvooe** [comment]
@DreadPirateShawn Thank for the contribution. This looks like a duplicate of #383. I'll merge the PR that signs their commit first. ;)

@moxiegirl PTAL.

**Comment by DreadPirateShawn** [comment]
Hmm, what do you mean by signing the commit?

All I can find reference to is the `-S` flag on git commit... though since I fixed the typo using the GitHub build-in web editor, that doesn't seem relevant...

Even if the other committer does sign their commit first, I'd appreciate knowing what to do next time. (FWIW, I checked CONTRIBUTING.md but didn't find clarification there either.)

**Comment by moxiegirl** [comment]
@DreadPirateShawn Thank you for the contribution.  And, I'm sorry you had problems finding contribution information.  This contains information about configuring for signature and what it means in Docker's contribution work flow.

http://docs.docker.com/project/set-up-git/#set-your-signature-and-an-upstream-remote

Once you have this configured, you can just `git commit -s -m <message>` before your push and you'll be g2g.

**Comment by DreadPirateShawn** [comment]
Much obliged! I think that translates to "submit a new PR with a signed commit", in order to avoid any sort of rebasing this commit. (Also, I found a second similar typo.)

New PR #389 submitted, with a signed commit and everything. :-)

This PR can presumably be closed, though I'll defer to you for confirmation.

**Pull request closed without merging**
