### PR TITLE
Manifest PUT should return 202 Accepted status

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @dmp42 @dmcgowan

**Comment by stevvooe** [comment]
This change is per the specification: https://github.com/docker/distribution/blob/master/doc/SPEC.md#on-success-accepted.

Arguably, 202 Accepted is fine but we may want to change this. Fortunately, the docker engine client will accept any 2xx or 3xx response, so we have some room to figure this out.

For now, we should merge this. I've filed #142 for us to look into the problem.

**Comment by jlhawn** [comment]
LGTM

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
