### PR TITLE
[carry #1972] Update schema2 builder to take media type

### PR DESCRIPTION
**Pull request by dmcgowan**
Modify manifest builder so it can be used to build manifests with different configuration media types.

### CODE REVIEW

**Comment by dmcgowan** [comment]
Ping @tonistiigi @aaronlehmann @stevvooe

**Comment by tonistiigi** [comment]
LGTM

The name of the PR/commit is wrong though. This is just updating the builder not changing the manifest spec.

**Comment by dmcgowan** [comment]
updated commit comment

**Comment by stevvooe** [comment]
Shouldn't the mediatype be a property of the builder?

**Comment by dmcgowan** [comment]
@stevvooe I think the more correct method would be to just have the builder initialized with a descriptor. Creating the descriptor from a byte array is not something that should be the responsibility of the builder.

**Comment by stevvooe** [comment]
@dmcgowan The builder only builds _one_ kind of mediatype. I don't see why this would be taken as an argument.

**Pull request merged**
