### PR TITLE
Allow modtime to be a few seconds off on TestStatCall

### LINKED ISSUE #71: Storage driver TestStatCall modtime granularity
Currently tests for Stat() call require modtime to be **exactly** to the same be with the current time. On cloud machines, that simply can't be the case and clocks can be several seconds off. 

```go
	if start.After(fi.ModTime()) {
		c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
	}

	if fi.ModTime().After(expectedModTime) {
		c.Errorf("modtime %s after file created (%v)", fi.ModTime(), expectedModTime)
	}
```

Even if the time spent on the wire gets longer, the test case would simply fail:
I was testing this with azure driver and encountered a failure due to one-second off, here's that:

    c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
    ... Error: modtime 2015-01-16 20:10:02 +0000 UTC before file created (2015-01-16 12:10:03 -0800 PST)

This should probably have some ɛ=±5s around the modtime value, because the point is to verify mtim works and sane. In this case even ±60s should be ok. How about:

```go
	if start.Add(time.Second*epsilon).After(fi.ModTime()) {
		c.Errorf("modtime %s before file created (%v)", fi.ModTime(), start)
	}

	if fi.ModTime().After(expectedModTime.Add(time.Second*epsilon)) {
		c.Errorf("modtime %s after file created (%v)", fi.ModTime(), expectedModTime)
	}
```

lmk if you agree and I can send the patch. cc: @stevvooe

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
(Follow up to discussion at #71)

This prevents Stat tests on storage drivers to randomly fail due to timestamp differences (+-) between test machine and cloud storage providers. Usually cloud storage providers do not provide any timestamp accuracy guarantees.(in Azure case, where Windows Servers used, ntp guarantee is way more than a few seconds).

This test could also very well fail due to network latency on the test machine or which millisecond of the second the upload is completed.

This change makes the test case failing less due to network or such time syncing issues by adding ɛ=±10s to the time checks. Also removed a commented out code snippet. Anyway, modtime should not be used like an ETag to verify freshness of the file as no cloud storage provider also guarantees that time won't go backwards after an update (because storage frontends might have different timestamps and file can just get a smaller modtime).

(closes #71) cc: @stevvooe @BrianBland 

Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
In #71, we had agreed to using modify plus sleep, rather than an epsilon. What happened to that approach for this test?

**Comment by ahmetalpbalkan** [comment]
We will need this anyway to check if the time returned is sane but I saw that test code was not doing any second write. So I thought maybe write-sleep-write is not the intended test case here. Should we also check that time is not staying the same by adding another write?

**Comment by stevvooe** [comment]
@ahmetalpbalkan Sorry, I missed your question.

Yes, let's please modify the test to check for the following properties:

1. write(f0)-sleep(epsilon)-write(f0)-sleep(epsilon) results in monotonically increasing modtime.
2. write(f0)-sleep(epsilon)-write(f1)-sleep(epsilon) results in monotonically increasing modtime on separate file.

I think this captures the compromise and makes the test check what we really care about.

**Comment by ahmetalpbalkan** [comment]
> [...] makes the test check what we really care about.

to be clear, in this case, do we care about
a. monotonically increasing modtime OR
b. server time is the same with the client-side (it's not insanely off)
?

**Comment by stevvooe** [comment]
@ahmetalpbalkan We only care that the times are monotonically increasing with some epsilon. Drift between server and client can be managed elsewhere.

**Comment by ahmetalpbalkan** [comment]
Got it. Then this test should definitely not use time.Now(). I'll fix this later today and ping you again. Thanks.

**Comment by ahmetalpbalkan** [comment]
@stevvooe started working on this. however not sure what the following test is meant for:

> (2) write(f0)-sleep(epsilon)-write(f1)-sleep(epsilon) results in monotonically increasing modtime on separate file.

also the sleeps at the end doesn't make sense to me. what I've been thinking is:

1. write(file1, data1)
2. fi = stat(file1)
3. created = fi.ModTime()
4. sleep(10)
4. write(file1, data2)
5. fi = stat(file1)
6. if fi.ModTime().Before(created) { error("modtime is before creation time") }

Another **important point**, there is no notion of sub directories in Azure Blob Storage. For example if you have paths like `a/b/c.txt`, `a/b/d.txt`, you cannot get Stat about `a/b/` because it's a virtual directory and it vanishes once you delete `c.txt` and `d.txt`. I cannot return `ModTime` about dirs in Azure case (unless I traverse all its sub-files and find highest modtime = expensive). The `TestStatCall` actually tests this (modtime on dirs). I don't know how to proceed.

**Comment by stevvooe** [comment]
> also the sleeps at the end doesn't make sense to me.

Sleeps at the end are necessary for eventual consistency to converge. Most systems may return immediately but some slop here will allow for the backend to catch up, if necessary.

You're approach is probably fine but I'd suggest trying to change the test as little as possible. It only needs to change to be relative and robust to drift. The examples I provided above are merely illustrative.

> Another important point, there is no notion of sub directories in Azure Blob Storage. For example if you have paths like a/b/c.txt, a/b/d.txt, you cannot get Stat about a/b/ because it's a virtual directory and it vanishes once you delete c.txt and d.txt. I cannot return ModTime about dirs in Azure case (unless I traverse all its sub-files and find highest modtime = expensive). The TestStatCall actually tests this (modtime on dirs). I don't know how to proceed.

All the other drivers managed to implement stat on directories without the existence of directories. The stat result of a directory just reports a path and that it is a directory, which means it has children when queried as a prefix. We use it differently from a real directory, in that it is not explicitly created but it is listed. Regarding ModTime, directories don't need to support it. Please see the comment here: https://github.com/docker/distribution/blob/master/storagedriver/testsuites/testsuites.go#L735.

**Comment by ahmetalpbalkan** [comment]
@stevvooe thanks, based on your comment, removed the modtime check for dirs from the test and pushed 8de06ab.

**Comment by ahmetalpbalkan** [comment]
this fails the TestStatCall tests in `inmemory` driver. there must be some issue with updating modtime in that.

**Comment by stevvooe** [comment]
Please rebase after merge of #111.

**Comment by ahmetalpbalkan** [comment]
rebased

**Comment by stevvooe** [comment]
LGTM!

**Comment by dmp42** [comment]
LGTM

**Pull request merged**
