### PR TITLE
Adds "storageclass" configuration parameter for S3 driver.

### PR DESCRIPTION
**Pull request by BrianBland**
Defaults to STANDARD, also supports REDUCED_REDUNDANCY.

Addresses #753

### CODE REVIEW

**Comment by RichardScothern** [comment]
Is it possible to test this by checking the storage class in the response header?

**Comment by BrianBland** [comment]
@RichardScothern Test added :+1:

**Comment by stevvooe** [comment]
LGTM

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
