### PR TITLE
31may2016 docs updates

### PR DESCRIPTION
**Pull request by SvenDowideit**
@RichardScothern can you please confirm that #1741 and #1748 are fixes that apply to the current release?

### CODE REVIEW

**Comment by SvenDowideit** [comment]
I have one more PR that i want to make and cherry-pick

**Comment by RichardScothern** [comment]
I confirm that they are.

**Comment by SvenDowideit** [comment]
sweet - I'm hoping to add #1759 to this in the next day or so.

**Comment by SvenDowideit** [comment]
will add #1762 when that's merged.

**Comment by SvenDowideit** [comment]
OK, done. that's alot of docs debt paid :(

**Comment by joaofnfernandes** [comment]
Tested and LGTM, but the build is failing with
```
link error: (in page registry/index.md) /docker-trusted-registry/overview.md
```
I don't know what's causing the failure, since that overview.md file exists in the DTR repo.

**Comment by SvenDowideit** [comment]
yeah, that's due to the tests here being built with only the oss docs - I've an action item for out meeting that's related.

**Pull request merged**
