### PR TITLE
Breakup common package

### PR DESCRIPTION
**Pull request by stevvooe**
Catchall common packages are generally an indication of bad organization, so we are getting rid of it while it is small. Mostly, types were moved to other, more relevant packages or a new package was created. Please see the individual commits for details.

This addresses items discussed in #6.

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @dmp42 @dmcgowan @jfrazelle @icecrime @jlhawn

**Comment by dmp42** [comment]
LGTM

**Comment by icecrime** [comment]
Are we creating a `collections` package only for `type StringSet map[string]struct{}`?

**Comment by stevvooe** [comment]
@icecrime Yes. I'm not tied to the concept of a `collections` package. Hopefully, this avoids a million definitions of stringsets where they are used. Alternatively, we can just move this back into `auth/token` and make it private.

Let me know what you prefer.

**Comment by icecrime** [comment]
You know better, but if it's *only* used in `auth/token` let's just have it there.

**Comment by stevvooe** [comment]
@icecrime Fixed. ;)

**Comment by BrianBland** [comment]
LGTM

**Pull request merged**
