### PR TITLE
Expose Signatures() on Repository

### PR DESCRIPTION
**Pull request by ncdc**
Add a SignatureService and expose it via Signatures() on Repository so
external integrations wrapping the registry can access signatures.

Signed-off-by: Andy Goldstein <agoldste@redhat.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM.

Would it be possible to update `revisionstore.go` to use `SignatureService`?

**Comment by ncdc** [comment]
Do you mean that you'd like the implementations of getSignatures and putSignature in revisionstore.go to move into signaturestore.go, and have revisionStore then use SignatureService?

**Comment by stevvooe** [comment]
@ncdc Yea, that would be preferable.

**Comment by ncdc** [comment]
Will do!

**Comment by stevvooe** [comment]
LGTM!

**Pull request merged**
