### PR TITLE
switch to v1 and remove .image

### PR DESCRIPTION
**Pull request by vieux**
plugins are going out of experimental so let's bump to v1, also @stevvooe suggested we remove `.image`

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
@stevvooe : Now that plugin config is in v1, can we add it to the list of media types at https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md ?

**Comment by stevvooe** [comment]
@anusha-ragunathan Yes, please. Also, do we have a spec in distribution for the plugin config?

**Comment by vieux** [comment]
tests are green now. I'm pushed the doc change

**Pull request merged**
