### PR TITLE
azure: revendor + remove hacky solution in is404

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Removing the temporary workaround in is404() method by re-vendoring
the azure-sdk-for-go.

cc: @yuwamsft

### CODE REVIEW

**Comment by dmcgowan** [comment]
Missing vendor.conf change

**Comment by ahmetalpbalkan** [comment]
@dmcgowan  argh.  fixed. I wonder why a good alternative like [govendor](https://github.com/kardianos/govendor) was not picked. 😕

**Comment by dmcgowan** [comment]
@ahmetalpbalkan consistency, Docker is using it, plus it is very lightweight and easy. We just wanted something that works better than godep and robust enough to use until go creates an official tool.

Also looks like circleci finally ran for this PR.

LGTM

**Comment by dmcgowan** [comment]
Ping @yuwamsft

**Comment by dmcgowan** [comment]
@ahmetalpbalkan needs rebase

Would you also mind getting another azure sdk maintainer to verify and give an LGTM

**Comment by stevvooe** [comment]
LGTM

Please rebase.

**Comment by dmcgowan** [comment]
I went ahead and rebased, will merge when green

**Comment by ahmetalpbalkan** [comment]
I am no longer with Microsoft, I think Yu (cc'd above) would be the new maintainer if I recall correctly. You can reach out to [@]friism to make sure who the new maintainer(s) are.

**Pull request merged**
