### PR TITLE
doc: modify markdown format in distribution.md

### PR DESCRIPTION
**Pull request by dtan4**
Modify Markdown List format to generate appropriate preview in GitHub.

### Before

distribution_distribution_md_at_master_ _docker_distribution

### After

distribution_distribution_md_at_8baa5386250538364518c95a6a8b5917f8af65d0_ _docker_distribution

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks!

**Comment by stevvooe** [comment]
LGTM! Could you please sign your commit?

**Comment by thaJeztah** [comment]
@stevvooe Looks like you could use https://github.com/jfrazelle/gh-patch-parser :)

**Comment by dtan4** [comment]
@stevvooe  Just signed && force pushed :octocat: 
Please check again.

**Comment by stevvooe** [comment]
@dtan4 Thank you for the contribution!

**Pull request merged**
