### PR TITLE
docs: Small typo fix in config.md

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**
Signed-off-by: Ahmet Alp Balkan <ahmetalpbalkan@gmail.com>

### CODE REVIEW

**Comment by dmp42** [comment]
Typographic quote (’), my my that's classy :)

**Comment by ahmetalpbalkan** [comment]
@dmp42 I have plans to fix all the docker docs but they’re just huge. :D

**Comment by RichardScothern** [comment]
Do we want a normal quote @dmp42 ?

LGTM

**Comment by RichardScothern** [comment]
@ahmetalpbalkan would you mind normalizing the quote to '  for consitency's sake/

**Comment by ahmetalpbalkan** [comment]
@RichardScothern  Done.

**Comment by RichardScothern** [comment]
:100:

**Pull request merged**
