### PR TITLE
documentation for name validation grammar

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @dmcgowan

**Comment by dmcgowan** [comment]
I assume this is just defining the exist grammar, not necessarily what we would expect to feed into discovery. If we are going to be DNS based the first element cannot contain a "_" or begin with a number. However this change should reflect what is currently support and no what is proposed. In that case LGTM

**Comment by stevvooe** [comment]
@dmcgowan This is supposed to capture the current constraints. I'll have to make a few edits for this be correct.

**Comment by stevvooe** [comment]
@dmcgowan Updated. This grammar should be a superset of the DNS-based one and document the current constraints.

**Comment by dmcgowan** [comment]
It is not a superset if we are allowing `:<port>` in the first component, however for documenting current constraints LGTM

**Comment by stevvooe** [comment]
@dmcgowan Should we modify the specification here to include colon or will that conflict?

**Comment by dmcgowan** [comment]
This logic matches the code so I think this PR should be merged as is. The larger discussion about number of components and colons should happen in the namespace PR.

**Pull request merged**
