### PR TITLE
Exporting GCS driver parameters

### PR DESCRIPTION
**Pull request by arschles**

### CODE REVIEW

**Comment by RichardScothern** [comment]
hi @arschles .  What is the motivation for this?  (also the build is broken)

**Comment by arschles** [comment]
Hey @RichardScothern - I made this change so that the process for creating a new GCS client was more documentable and type-safe. Currently, the godoc for gcs (not shown at godoc.org because it requires the `include_gcs` build flag) shows the following as one of the two ways to create a new GCS client:

```go
func New(params driverParameters) (storagedriver.StorageDriver, error) {
```

Since `driverParameters` is not exported, there's no documentation on it, and the only other way to create one (implicitly) is with the `FromParameters` func.

I hope that's a clear enough explanation of my motivation for this change.

Also, I'll fix the tests as soon as I can. Thanks for reminding me of that.

**Comment by RichardScothern** [comment]
@arschles : the driver is instantiated within the registry from the values in the config file.  This is documented here: https://github.com/docker/distribution/blob/master/docs/storage-drivers/gcs.md.

Do you intend to call `NewDriverParameters`?

**Comment by arschles** [comment]
@RichardScothern yep, I do intend to call `NewDriverParameters` because I'm not going to be using the registry.

**Comment by RichardScothern** [comment]
I see.  Do you see a need for this function in other drivers?

**Comment by arschles** [comment]
@RichardScothern I wouldn't need it in other drivers, but I would like to use it in other programs that don't want to use the factory and use the implementations directly.

There's a related conversation about using the level of abstraction just below the factory/registration layer [here](https://github.com/deis/builder/pull/262#discussion_r56720200), and I think this change would help move in that direction.

Anyway, I'll push a fix for the tests shortly.

**Comment by arschles** [comment]
@RichardScothern I may have a fix for the tests, but I'm finding two things of note that are making verifying my fix a bit more difficult:

- `make test` doesn't fail on the code as it exists in this branch now
- `make test-full` fails intermittently with a panic (see below)

Also, generally speaking is there a build target I can run that mirrors what CircleCI ran to produce the failure?

#### `make test-full` panic trace

```console
SIGQUIT: quit
PC=0x5f17b m=0

goroutine 0 [idle]:
runtime.mach_semaphore_wait(0x1003, 0x0, 0x4e3da, 0x55c080, 0x5dd71, 0x6569e0, 0x51d39, 0xffffffffffffffff, 0x3b8a5, 0x7fff5fbff58c, ...)
	/usr/local/go/src/runtime/sys_darwin_amd64.s:407 +0xb
runtime.semasleep1(0xffffffffffffffff, 0x3b8a5)
	/usr/local/go/src/runtime/os1_darwin.go:385 +0xe5
runtime.semasleep.func1()
	/usr/local/go/src/runtime/os1_darwin.go:401 +0x29
runtime.systemstack(0x7fff5fbff590)
	/usr/local/go/src/runtime/asm_amd64.s:278 +0xab
runtime.semasleep(0xffffffffffffffff, 0x0)
	/usr/local/go/src/runtime/os1_darwin.go:402 +0x36
runtime.notesleep(0x657090)
	/usr/local/go/src/runtime/lock_sema.go:169 +0x100
runtime.stopm()
	/usr/local/go/src/runtime/proc1.go:1128 +0x112
runtime.findrunnable(0xc820024a00, 0x0)
	/usr/local/go/src/runtime/proc1.go:1530 +0x69e
runtime.schedule()
	/usr/local/go/src/runtime/proc1.go:1639 +0x267
runtime.park_m(0xc8280b7980)
	/usr/local/go/src/runtime/proc1.go:1698 +0x18b
runtime.mcall(0x7fff5fbff710)
	/usr/local/go/src/runtime/asm_amd64.s:204 +0x5b

goroutine 1 [chan receive, 10 minutes]:
testing.RunTests(0x506700, 0x64d8f0, 0x1, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820045f08, 0x0)
	/usr/local/go/src/testing/testing.go:494 +0x70
main.main()
	github.com/docker/distribution/registry/storage/driver/inmemory/_test/_testmain.go:54 +0x116

goroutine 17 [syscall, 10 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 18 [chan receive, 3 minutes]:
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*suiteRunner).runTest(0xc82009e080, 0xc820019810, 0xc8bf490c30)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:801 +0x57
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*suiteRunner).run(0xc82009e080, 0xc8200101c0)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:606 +0x27e
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.Run(0x44d220, 0xc8200101c0, 0xc8200106c0, 0x2)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/run.go:92 +0x43
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.RunAll(0xc8200106c0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/run.go:84 +0xc3
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.TestingT(0xc82008c000)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/run.go:72 +0x1e4
github.com/docker/distribution/registry/storage/driver/inmemory.Test(0xc82008c000)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/registry/storage/driver/inmemory/driver_test.go:12 +0x21
testing.tRunner(0xc82008c000, 0x64d8f0)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 19 [select, 3 minutes]:
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*resultTracker)._loopRoutine(0xc82008c090)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:452 +0x3a2
created by github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*resultTracker).start
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:432 +0x35

goroutine 141 [runnable]:
github.com/docker/distribution/registry/storage/driver/inmemory.(*file).WriteAt(0xc8280e6f40, 0xc88ace2000, 0x8000, 0x8000, 0xc200000, 0x2a2ee08, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/registry/storage/driver/inmemory/mfs.go:302 +0x87
github.com/docker/distribution/registry/storage/driver/inmemory.(*writer).Write(0xc8b54aadc0, 0xc88ace2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/registry/storage/driver/inmemory/driver.go:270 +0x20d
io.copyBuffer(0x7b7358, 0xc8b54aadc0, 0x2a2ee58, 0xc8b54aade0, 0xc88ace2000, 0x8000, 0x8000, 0xc200000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:383 +0x2c9
io.Copy(0x7b7358, 0xc8b54aadc0, 0x2a2ee58, 0xc8b54aade0, 0xc8b54aadc0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:351 +0x64
github.com/docker/distribution/registry/storage/driver/testsuites.(*DriverSuite).TestWriteReadLargeStreams(0xc8200101c0, 0xc8bf490e10)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/registry/storage/driver/testsuites/testsuites.go:288 +0x49c
reflect.Value.call(0x44d220, 0xc8200101c0, 0x6313, 0x453430, 0x4, 0xc88acdff10, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x44d220, 0xc8200101c0, 0x6313, 0xc88acdff10, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkTest.func1(0xc8bf490e10)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:763 +0x498
github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall.func1(0xc82009e080, 0xc8bf490e10, 0xc8b54aaaa0)
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:657 +0x6f
created by github.com/docker/distribution/vendor/gopkg.in/check%2ev1.(*suiteRunner).forkCall
	/Users/aaronschlesinger/gocode/src/github.com/docker/distribution/vendor/gopkg.in/check.v1/check.go:658 +0x29e

rax    0xe
rbx    0x1003
rcx    0x7fff5fbff518
rdx    0x7fff5fbff590
rdi    0x1003
rsi    0x6569e0
rbp    0x656f80
rsp    0x7fff5fbff518
r8     0x656f80
r9     0x0
r10    0x0
r11    0x286
r12    0x8
r13    0x503a9b
r14    0x9
r15    0x8
rip    0x5f17b
rflags 0x286
cs     0x7
fs     0x0
gs     0x0
```

**Comment by RichardScothern** [comment]
`DOCKER_BUILDTAGS=include_gcs make test` will run the gcs tests.

`make test-full` is panicing because it runs for longer than test timout limit

**Comment by RichardScothern** [comment]
hi @arschles .  Any update on this?

**Comment by dmcgowan** [comment]
Closing, failing tests and no updates. Feel free to rebase and open a new PR if the tests get resolved.

**Pull request closed without merging**
