### PR TITLE
[release/2.7 backport] Add reference.ParseDockerRef utility function

### PR DESCRIPTION
**Pull request by thaJeztah**
backport of https://github.com/docker/distribution/pull/2786 for the release/2.7 branch
to address https://github.com/containerd/containerd/issues/3031 if included in a 2.7.x patch release

ParseDockerRef normalizes the image reference following the docker
convention. This is added mainly for backward compatibility. The reference
returned can only be either tagged or digested. For reference contains both tag
and digest, the function returns digested reference, e.g.

    docker.io/library/busybox:latest@sha256:7cc4b5aefd1d0cadf8d97d4350462ba51c694ebca145b08d7d41b41acc8db5aa

will be returned as

    docker.io/library/busybox@sha256:7cc4b5aefd1d0cadf8d97d4350462ba51c694ebca145b08d7d41b41acc8db5aa.

### CODE REVIEW

**Comment by thaJeztah** [comment]
@dmcgowan @caervs - no idea if there's plans to do a 2.7.2 release, but thought I'd open a backport (in case there are plans)

**Comment by thaJeztah** [comment]
ping @dmcgowan PTAL

**Comment by thaJeztah** [comment]
rebased to make the vendor-check pass (which should be fixed by https://github.com/docker/distribution/pull/3001)

**Comment by thaJeztah** [comment]
ping @dmcgowan @manishtomar @stevvooe PTAL

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
