### PR TITLE
[WIP] registry/storage/driver: checking that non-existent path returns PathNotFoundError

### PR DESCRIPTION
**Pull request by stevvooe**
Issue #1186 describes a condition where a null tags response is returned when
using the s3 driver. The issue seems to be related to a missing
PathNotFoundError in s3. This change adds a test for that to get an idea of the
lack of compliance across storage drivers. If the failures are manageable,
we'll add this test condition and fix the s3 driver.

Don't merge this.

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
ok, so oss, rados, swift & s3 all fail this check :cry: 
gcs, filesystem and inmemory :+1:

**Comment by stevvooe** [comment]
Fixing s3.

Let's bring the maintainers of oss, rados and swift to provide a fix.

swift: @nevermosby @lebauce @ojacques 
oss: @denverdino 
rados: @gierschv @noahdesu 

Please make a PR with the fix against stevvooe:check-storage-drivers-list-path-not-found and we'll merge in to this branch to get CI fix.

**Comment by stevvooe** [comment]
@nevermosby @lebauce @ojacques Any chance getting a fix for this? We'll have to turn off the swift driver in the default build if we can't get it in compliance.

**Comment by nevermosby** [comment]
@stevvooe I am working on it. Will release the fix ASAP.

**Comment by stevvooe** [comment]
Status: waiting on @lebauce LGTM in stevvooe/distribution#4.

**Comment by stevvooe** [comment]
@denverdino Looks like oss is still failing here.

**Comment by RichardScothern** [comment]
All test passing :joy: LGTM

**Comment by stevvooe** [comment]
Finally.

**Pull request merged**
