### PR TITLE
Log a completed request at the end of the dispatch method

### PR DESCRIPTION
**Pull request by dmathieu**
Dispatch updates the context, replacing the request object.
If we log the end of a request in ServeHTTP, we don't get the updated one and will therefore not log all we need.

For example, when the request is authenticated, we add the `user.email` field to the log fields.
The previous behavior wasn't logging that field.

### CODE REVIEW

**Comment by dmathieu** [comment]
ping @dmcgowan could we get a review on this?

**Comment by dmathieu** [comment]
Ping @stevvooe too.
This is preventing us from searching for specific requests in splunk, making internal issues investigations quite harder.

**Comment by stevvooe** [comment]
@dmathieu Thanks for the PR!

Unfortunately, the proposed fix will not log a request if the route is missed. Typically, you can write a log message with context value and then correlate with request id. We do this to avoid polluting every log message with too much information (arguably, we need to reduce this massively).

The other option might be to add a log message surrounding the access controller call. That would be generally useful for auditing and meet the use case. Would that work?

**Comment by dmathieu** [comment]
I'm not sure how the missing route is an issue. The defer only logs for success requests, with a status >= 200 and <= 399.
So 404 will never be logged anyway.

**Comment by dmathieu** [comment]
Wrapping this in the access controller would probably work, and I'm fine doing that if you believe this is the right way, though I'm not sure the responsibility of logging the end of a request should be in an access controller.

**Comment by stevvooe** [comment]
@dmathieu The root issue is that `errcode` shouldn't be used within access controllers. These are a handler level mapping. We commonly see PRs like this that seem to not work in full, because of the attempt to use errcode, elsewhere. We can usually tell this by a rise in complexity of error handling. 

Because this is application level business logic, it should use errors that are part of that domain. They should use specialized error types, equivalent to `auth.Challenge`.

**Comment by dmathieu** [comment]
@stevvooe sorry, I don't understand your reply.
This change doesn't touch `errcode`, and it's not within an access controller.

**Comment by stevvooe** [comment]
@dmathieu Sorry, I've mixed up this issue with another. Apologies.

Each log message has a request id. If there is a log message before and after the access controller (in `app.go`, not the access controller itself, you can correlate the `user.email` with the request because the message with the identifying information and request status information will have the same request id.

I think we already do some logging of `user.name`, so check that that is not already there.

Does that make sense?

**Comment by dmathieu** [comment]
Relying on request_id and searching for the valid user is unfortunately not a good solution.
In addition to complicating things, the distribution public API allows us to set our own logger options which can be anything. This API is broken as those fields, when set are not actually respected.

In our case, we need to set a `source=com.domain.app.environment` field on every log to be able to filter splunk results based on a specific app.

I'm fine with any solution, even moving the logging to the access controller as weird as it sounds, but searching for older logs to find some information is unfortunately not a good solution.

**Comment by stevvooe** [comment]
> In addition to complicating things, the distribution public API allows us to set our own logger options which can be anything. This API is broken as those fields, when set are not actually respected.

What do you mean "the distribution public API"? We don't really have an API to do this. How are these not respected?

**Comment by dmathieu** [comment]
I mean the public Go API. [GetLoggerWithFields](https://github.com/docker/distribution/blob/b6e0cfbdaa1ddc3a17c95142c7bf6e42c5567370/context/logger.go#L58) allows us to set custom logging fields, which are then not respected as the wrong context is being used.

**Comment by stevvooe** [comment]
@dmathieu That is not what that function does. All it does is give you back a logger from the current context with the extra fields. You have to place the logger back into the context or pass the logger around for the fields to be visible to later callers.

**Comment by dmathieu** [comment]
Yes, we got that thank you.
But as the wrong context is later being used, those fields are not actually visible. This is that this PR fixes.

**Pull request closed without merging**
