### PR TITLE
Replace godep with vndr

### PR DESCRIPTION
**Pull request by dmcgowan**
Vndr has a simpler configuration and allows pointing to forked packages. Additionally other docker projects are now using vndr making vendoring in distribution more consistent.

Updates letsencrypt to use fork.
No longer uses sub-vendored packages.

See https://github.com/lk4d4/vndr

### CODE REVIEW

**Comment by aaronlehmann** [comment]
cc @lk4d4

**Comment by LK4D4** [comment]
I'm all for this :)

**Comment by aaronlehmann** [comment]
Noticed that a `vendor/rsc.io/letsencrypt/vendor/gopkg.in/square/go-jose.v1/json/testdata/code.json.gz` file is added. This doesn't seem right.

**Comment by dmcgowan** [comment]
It is a remove, binary removals show up in a confusing manner in the file list

```.diff
diff --git a/vendor/rsc.io/letsencrypt/vendor/gopkg.in/square/go-jose.v1/json/testdata/code.json.gz b/vendor/rsc.io/letsencrypt/vendor/gopkg.in/square/go-jose.v1/json/testdata/code.json.gz
deleted file mode 100644
index 0e2895b..0000000
Binary files a/vendor/rsc.io/letsencrypt/vendor/gopkg.in/square/go-jose.v1/json/testdata/code.json.gz and /dev/null differ

```

**Comment by dmcgowan** [comment]
@aaronlehmann I see what you are talking about, looks like a Github bug. In the file list shows up as red, but in the other list shows up as green....

screenshot from 2016-11-29 20-44-11

screenshot from 2016-11-29 20-44-51

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
