### PR TITLE
Add Taylor

### PR DESCRIPTION
**Pull request by mikebrow**
Merging @owtaylor  commits to the OCI manifest PR.

### CODE REVIEW

**Comment by owtaylor** [comment]
I repushed my brach with sign-offs - sorry for not having them earlier.

**Comment by mikebrow** [comment]
@owtaylor yeah I tried to do a pull merge / rebase of your changes but got some test errors and the sign-off issues.  Could you just rebase and push your PR to this repo as a dependent PR? Then we can merge both when the tests pass.

**Comment by owtaylor** [comment]
Not quite sure what you mean by dependent PR. I created a pull request https://github.com/mikebrow/distribution/pull/1 against your ocitype branch - I think if that is merged to your ocitype branch, #2076 will be updated to include my commits.

**Comment by mikebrow** [comment]
Your branch is already dependent.. just needs to be pushed. Ah I see you did! Thanks!

**Pull request closed without merging**
