### PR TITLE
disable schema1 by default, add a config flag to enable it

### PR DESCRIPTION
**Pull request by vikstrous**
port of #2473

Signed-off-by: Viktor Stanchev <me@viktorstanchev.com>

### CODE REVIEW

**Comment by vikstrous** [comment]
I don't understand the jenkins failures. Any ideas? @stevvooe

**Comment by stevvooe** [comment]
@dmcgowan PTAL

**Comment by stevvooe** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
