### PR TITLE
add repo and tag deletion event

### PR DESCRIPTION
**Pull request by manishtomar**
Whenever a repo or tag is deleted an event is sent out via the regular notification channels. When repo is deleted the event will only contain repo name but not tag or digest. When tag is deleted the event it will have repo and tag but not digest. There is new interface `RepositoryRemover` containing method to delete the repo. Its implemented by internal `registry` instance. To capture the event the registry instance is also stored as `RepositoryRemover` in the application context.

### CODE REVIEW

**Comment by dmcgowan** [comment]
LGTM

This approach looks fine to me, maybe @stevvooe or @aaronlehmann can give it a quick look to see if the event looks consistent to them.

**Comment by dmp42** [comment]
LGTM.

@manishtomar why is Circle failing?

**Comment by manishtomar** [comment]
@dmp42 I fixed the circle failure but I don't know why Jenkins is failing with integration tests. The logs are not very clear. If you don't mind can you have a quick glance and let me know whats wrong? If not, I can try digging into it.

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
