### PR TITLE
Add annotated example for adding header; +spelling

### PR DESCRIPTION
**Pull request by mrwacky42**
This adds a variable to help nginx add the
Docker-Distribution-Api-Version when using basic auth, and not add the
header when it sees it from the upstream.

Also fix some minor spelling/grammar issues.

This should help with issues like #1028.
However, a better solution is probably for `docker pull` to not fall back to the v1 API when presented with a 401.

### CODE REVIEW

**Comment by RichardScothern** [comment]
Ping @dmp42

**Comment by mrwacky42** [comment]
Ping @dmp42

**Comment by dmp42** [comment]
Doc LGTM - though I have not reproduced the problem myself.
@RichardScothern ok with it?

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
