### PR TITLE
correct broken path to v2-registry-auth.png

### PR DESCRIPTION
**Pull request by bmillemathias**
the picture is not anymore in the repository so I use the external path

### CODE REVIEW

**Comment by stevvooe** [comment]
@mstanleyjones Could we just move this image back to the distribution repo? It is part of the spec.

**Comment by stevvooe** [comment]
@mstanleyjones PTAL

**Comment by mstanleyjones** [comment]
I thought I had a PR that did just this. I need to hunt it down or make one.

**Comment by stevvooe** [comment]
@mstanleyjones This is an image for specification. Should it not be a part of this repository?

**Comment by mstanleyjones** [comment]
Let's close this one. I've got another PR coming that puts this image back into this repo, and one in the docs repo that takes it out of there.

**Pull request closed without merging**
