### PR TITLE
Change confusing enpoint name

### PR DESCRIPTION
**Pull request by kyzh**
Since the actual port is 5003, it would make sense to name it local-5003 instead of local-8082

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

Please sign your commits.

**Comment by kyzh** [comment]
I found at least one other instance of the exact same issue.  
Should I add it to this PR?  

I will sign my commit for this PR and going forward, sorry.

**Comment by stevvooe** [comment]
@kyzh That is fine to add other nits to the PR.

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
