### PR TITLE
Integration Tests: Generate the certificate directory with a pretest script

### LINKED ISSUE #1690: Cannot checkout project on Windows machine
It's not possible to checkout the project on a windows machine, causing `go get` to fail, and for example, some build to fail (see https://ci.appveyor.com/project/calavera/engine-api/build/247).

It seems Windows doesn't like path with `:` in it `fatal: cannot create directory at 'contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument` :sweat_smile:.

```
C:\Users\demeester\go\src\github.com\docker
λ git clone https://github.com/docker/distribution.git
Cloning into 'distribution'...
remote: Counting objects: 13957, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 13957 (delta 12), reused 0 (delta 0), pack-reused 13927
Receiving objects: 100% (13957/13957), 9.37 MiB | 641.00 KiB/s, done.
Resolving deltas: 100% (7338/7338), done.
Checking connectivity... done.
fatal: cannot create directory at 'contrib/docker-integration/generated_certs.d/localregistry:5440': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

### PR DESCRIPTION
**Pull request by dmcgowan**
Removes directories containing `:` from the git tree. The certificates generate the directory layout in a pre-test script which will get mounted for the docker container to use.

fixes #1690

### CODE REVIEW

**Comment by vdemeester** [comment]
@dmcgowan yay cool, thanks ! LGTM :angel:

**Comment by RichardScothern** [comment]
I don't have windows to test with but LGTM 🐱

**Comment by F21** [comment]
I also ran into this issue myself. I am able to clone your branch successfully on Windows: `git clone -b install-certs https://github.com/dmcgowan/distribution`

**Comment by Monomachus** [comment]
great, it's working, thank you

**Pull request merged**
