### PR TITLE
Change DELETE action from "*" to "delete"

### PR DESCRIPTION
**Pull request by nwt**
With token authentication, requiring the "*" action for DELETE requests
makes it impossible to administratively lock a repository against pushes
and pulls but still allow deletion.  This change adds a new "delete"
action for DELETE requests to make that possible.

### CODE REVIEW

**Comment by nwt** [comment]
Just saw #2120.

**Comment by nwt** [comment]
I'm reopening this in case it's preferable to #2120.

**Comment by stevvooe** [comment]
@nwt Need to confirm that `*` in a token appropriately matches delete.

**Comment by stevvooe** [comment]
@jlhawn PTAL

**Comment by jlhawn** [comment]
SGTM

**Comment by stevvooe** [comment]
LGTM

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
