### PR TITLE
Fix the wrong spell from `JOSE` to `JSON`

### PR DESCRIPTION
**Pull request by maquanyi**

### CODE REVIEW

**Comment by RichardScothern** [comment]
Your spelling change does not match the description of this PR.  Please also rebase and sign your commit.

**Comment by thaJeztah** [comment]
also looks like you accidentally included an extra commit

**Comment by RichardScothern** [comment]
In fact, JOSE is correct:
http://self-issued.info/docs/draft-ietf-jose-json-web-signature.html#rfc.section.4

**Comment by thaJeztah** [comment]
Oh, LOL, learned something new today!

**Pull request closed without merging**
