### PR TITLE
Add revisions list API

### PR DESCRIPTION
**Pull request by m-masataka**
Signed-off-by: Masataka Mizukoshi <m.mizukoshi.wakuwaku@gmail.com>
I want to get revisions list by API.
See #2286.

### CODE REVIEW

**Comment by stevvooe** [comment]
We don't really have model for revisions on the API-facing side. Could you tell me how they would work? Does this just list all manifests by digest?

**Comment by m-masataka** [comment]
In this implementation, I used the ``ManifestEnumerator`` interface.
This interface list up the digest that is located in revisions directory by using ``manifestRevisionsPathSpec``. 
So I diverted this interface.

**Comment by stevvooe** [comment]
@m-masataka Wouldn't this make more sense as `/v2/<name>/manifests/`? Similar to the changes present in the tags listing API change?

**Comment by m-masataka** [comment]
@stevvooe 
This API can list the manifests including old manifest (does't have current link).
Yes, this change is  like tag/list api changes.

**Comment by stevvooe** [comment]
Ok, so, let's make the route `/v2/<name>/manifests/`, rather that introduce a new API concept.

**Comment by dmcgowan** [comment]
Additions to specification or API are no longer being considered here. The specification has moved to https://github.com/opencontainers/distribution-spec

**Pull request closed without merging**
