### PR TITLE
Plugin integration test

### PR DESCRIPTION
**Pull request by dmcgowan**
- Add plugin push and pull tests. Tests that images pushed as plugins cannot be pulled as images and vice versa.
- Additional base image used for creating plugin rootfs
- Updates login to allow supply the email flag in less than docker 1.11. Needed to support 1.13 which removes the email flag.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
LGTM

**Comment by dmcgowan** [comment]
Going to wait until docker rc4 to merge this so I can update the test to run against 1.13 before merging.

**Comment by thaJeztah** [comment]
ping @dmcgowan what's the status on this one?

**Comment by dmcgowan** [comment]
Still one failure and waiting for the rc5 docker image to come out. Once that is updated and janky passes will merge.

**Pull request merged**
