### PR TITLE
Specify manifest schema version 1 media type

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
cc @jlhawn @dmcgowan

**Comment by dmcgowan** [comment]
LGTM

**Comment by jlhawn** [comment]
LGTM

**Comment by thaJeztah** [comment]
@stevvooe will it be necessary to officially register the mime-type(s)?  http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by stevvooe** [comment]
@thaJeztah We can. I am not sure we have the required specification coverage at this point. Is there a way we can reserve the "application/vnd.docker.*" space and then fill in as we have a complete specification? Ideally, the format settles for at least a few months before we go through this procedure.

**Comment by thaJeztah** [comment]
@stevvooe I'm not sure how the whole process for that works, just thought it would be nice to have it "official". Perhaps @ahmetalpbalkan has a colleague that knows? Given that they have registered a bunch (lol)

**Comment by thaJeztah** [comment]
Might be good to create a separate "tracker" issue for it ("register mime types"), to put it on the roadmap.

**Comment by stevvooe** [comment]
@thaJeztah Looking at the process, it seems it requires are specifications to be a lot further along. What are the benefits?

**Pull request merged**
