### PR TITLE
Add TrustId parameter to swift driver

### PR DESCRIPTION
**Pull request by humble00**
github/ncw/swift has added support for trust [1], so let's add it.

[1]https://github.com/ncw/swift/commit/8f232e4782787aee6ab31050e4aa75eb970b277c

### CODE REVIEW

**Comment by humble00** [comment]
Will Docker distribution CI get the newest github.com/ncw/swift lib? I have add trust support to github.com/ncw/swift. But CI reports it is not supported.

**Comment by nevermosby** [comment]
Hi @humble00 According to the error message of circleci, you need to:

1. update the value of "Rev" at `https://github.com/docker/distribution/blob/master/Godeps/Godeps.json#L99` for using the latest version of ncw/swift with additional "trustID" property

2. update the documentation about openstack v3 auth url in `https://github.com/docker/distribution/blob/master/docs/configuration.md` as I've found you got the v3 auth url updated in ncw/swift

3. go fmt your changed code

**Comment by humble00** [comment]
@nevermosby , I update the value of "Rev", but it doesn't work. How can I update the dependencies?

**Comment by nevermosby** [comment]
@humble00 I think u r good now for  jenkins and circleci since your code changes for ncw/swift have been included into your pull request.

**Comment by stevvooe** [comment]
LGTM

**Comment by humble00** [comment]
@RichardScothern ,I need this feature in our openstack project magnum. And the milestone is coming. Please have a look at this pr if you have time. Thank you.

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
