### PR TITLE
digest: remove stuttering ParseDigest function

### PR DESCRIPTION
**Pull request by stevvooe**
Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
Hold off on merging this for a bit...

**Comment by stevvooe** [comment]
Alright, please merge when building!

**Comment by dmcgowan** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM, but note that this change will have to be coordinated with docker/docker and docker/swarmkit, which both use this function. The moment swarmkit vendors a new distribution and fixes its calls to this function, docker will need to as well, otherwise swarmkit won't be vendorable anymore. It's probably worth creating PRs for both docker/docker and docker/swarmkit and merging them around the same time.

**Comment by dmcgowan** [comment]
This change does not remove the old function, so don't think there should be any difficulty vendoring

**Pull request merged**
