### PR TITLE
s3 Compatible: registry s3 driver support radosgw

### PR DESCRIPTION
**Pull request by wangmingshuai**
Now, registry s3 driver unsupport RadosGW. 
The pull request https://github.com/docker/distribution/pull/808 @lorieri aims to this issue. Regrettably,  pull request https://github.com/docker/distribution/pull/808 is not enough beacuse there are several amazon S3 REST API that registry used but RadosGW unsupport:

 - regionendpoit configurable (refer to https://github.com/docker/distribution/pull/808)
 - HEAD for object info (refer to https://github.com/docker/distribution/pull/808)
 - x-amz-copy-source-range (used when upload multi part)
 - x-amz-copy-source (used when upload multi part)
 - delete multiple objects (used when delele multiple objects )
 - complete upload multiple part need http header content-length (needed by RadosGW fix in https://github.com/AdRoll/goamz/pull/392)

This pull request  aims to fix S3 compatibility  mentioned above, AND this pull request should work with pull request https://github.com/AdRoll/goamz/pull/392

Signed-off-by: wangmingshuai <736808191@qq.com>

### CODE REVIEW

**Comment by stevvooe** [comment]
@wangmingshuai I am not sure we can consider this until AdRoll/goamz#389 is accepted. Also, please gofmt your code. The tests are currently failing.

Do we have any way of running the s3 testsuite against a RadosGW? Without this testsuite passing, I'd doubt this will work very well.

**Comment by wangmingshuai** [comment]
hi @stevvooe , we have done many tests in our environment , and it worked well . The related PR https://github.com/AdRoll/goamz/pull/392  has been merged . can you reconsider about this PR ?

**Comment by lorieri** [comment]
I would love if you keep my commits instead of copy and paste :)

**Comment by stevvooe** [comment]
@wangmingshuai The following needs to be done to get this merged:


- [ ] CI testing for this particular use case.
- [ ] Update the goamz dependency in Godeps.

Please ensure that @lorieri receives proper credit for his work by preserving the commits.

**Comment by wangmingshuai** [comment]
hi, @lorieri, thanks for the suggestion , my bad , I will wait your PR https://github.com/docker/distribution/pull/808 to be merged , and i will create a new PR to offer my code :)

**Comment by wangmingshuai** [comment]
hi @stevvooe  @lorieri , the new PR https://github.com/docker/distribution/pull/960 , and i don't understand the jenkins error. can you explain it ?

**Pull request closed without merging**
