### PR TITLE
Add plugin mediatype to distribution manifest.

### PR DESCRIPTION
**Pull request by anusha-ragunathan**
This is required for github.com/docker/docker/pull/25582

Signed-off-by: Anusha Ragunathan <anusha@docker.com>

### CODE REVIEW

**Comment by RichardScothern** [comment]
LGTM

**Comment by anusha-ragunathan** [comment]
Can we get this merged?

**Comment by dmcgowan** [comment]
I have 2 questions.

- Why `v0`, is this specification a work in progress, will we soon be adding another version and need a way to handle it. From the docker/docker PR it seems like it would make more sense on pull to explicitly look for the media types which are allowed and send the error if it is not found, rather than looking for this specific value.
- Speaking of specifications, is this format specified somewhere, I don't see a link in either PR.

**Comment by anusha-ragunathan** [comment]
@dmcgowan : The plugin manifest is a WIP and a stable v1 will be released in docker 1.13. Regarding working on the white-list (instead of the current blacklist approach), where can I find the list of "media types which are allowed"? A formal manifest specification document is also a WIP.

**Comment by dmcgowan** [comment]
LGTM

**Pull request merged**
