### PR TITLE
Convert to go modules.

### PR DESCRIPTION
**Pull request by SuperQ**
* Replace vendor.conf with go.mod.
* Fix aliases import of `github.com/dmcgowan/letsencrypt` fork.
* Updates all vendored code to latest releases where possible.

### CODE REVIEW

**Comment by sevki** [comment]
why is this abandoned? are there no plans to get this in the master?

**Comment by SuperQ** [comment]
@sevki Good question, I have a hard time getting Docker people to review things here.

**Comment by SuperQ** [comment]
Ugh, gometalinter is such a pain.

**Comment by SuperQ** [comment]
So, there are a bunch of errors I can't quite figure out with gometalinter.  Apparently this tool is deprecated and is replaced by [golangci-lint](https://github.com/golangci/golangci-lint). But that tool seems like it requires switching to Go modules first. :-/

**Comment by sevki** [comment]
oh wow. you've made  the tests pass!!!! :tada: :tada: :tada: @manishtomar can you take a look?

**Comment by SuperQ** [comment]
Yea, I cheated. I gave up after several hours of messing around with it. There are a bunch of `gometalinter` problems that are unrelated to switching to modules. So I disabled `make check` in the travis config. :frowning_face:

**Comment by sevki** [comment]
Maybe we can get some guidance from the docker folks

**Pull request closed without merging**
