### PR TITLE
Add Go coding style guidelines

### LINKED ISSUE #688: Make it clear that we adhere to Go's style guide
By review, we tend to enforce https://github.com/golang/go/wiki/CodeReviewComments. This should be an explicit requirement called out in contributing.md.

### PR DESCRIPTION
**Pull request by stevvooe**
Closes #688

cc @icecrime @dmp42 

Signed-off-by: Stephen J Day <stephen.day@docker.com>

### CODE REVIEW

**Comment by icecrime** [comment]
I like it, WDYT @LK4D4 @crosbymichael @jfrazelle @calavera @tiborvass?

**Comment by dmp42** [comment]
cc @docker/distribution-maintainers

**Comment by dmp42** [comment]
And LGTM!

**Comment by LK4D4** [comment]
It's supercool. Hard work to get golint passed on docker though :)

**Comment by RichardScothern** [comment]
Pithy.  LGTM.

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
