### PR TITLE
Couple of post-release Fixes

### LINKED ISSUE #390: Build instructions need to be in more prominent location
Tucking the build instructions away in the docs hides them from developers. Developers are more likely to consume the project through the README. We should either add the building section back to the README or link to it from the README.

cc @moxiegirl

### LINKED ISSUE #391: docs.docker.com/registry should be the top level page
Redirect isn't necessary if we rename the overview.md to index.md

### PR DESCRIPTION
**Pull request by moxiegirl**
Fixes #390 to add building link to README
Fixes #391 for registry top page

Signed-off-by: Mary Anthony <mary@docker.com>

### CODE REVIEW

**Comment by moxiegirl** [comment]
ping @dmp42 @stevvooe This should fix the registry issue Olivier.  I'll have a test server up shortly.

**Comment by stevvooe** [comment]
@moxiegirl In the future, try to only do one fix per PR. It will make reviewing and merging much faster.

**Comment by stevvooe** [comment]
LGTM!

**Comment by moxiegirl** [comment]
@stevvooe Yep, I'm trying to get more rigorous in that way...I learned from working with y'all. It is interesting what each team finds important in PR and the like.  Pretty soon I'll be like the perfect PR person cause I'm picking the best "DNA" of practice from each team.

**Pull request merged**
