### PR TITLE
move gorelic verbose option to config file, leave as false by default

### PR DESCRIPTION
**Pull request by avinson**
this is a new PR.. my first one had an extraneous else block

### CODE REVIEW

**Comment by avinson** [comment]
:(

**Comment by dmp42** [comment]
Configuration is a b.
@stevvooe will help you with that.

**Comment by RichardScothern** [comment]
You're code is close.  Just missing the field in the test file:

```
diff --git a/configuration/configuration_test.go b/configuration/configuration_test.go
index 1093722..5c5d68b 100644
--- a/configuration/configuration_test.go
+++ b/configuration/configuration_test.go
@@ -351,7 +351,7 @@ func copyConfig(config Configuration) *Configuration {
        }
        configCopy.Reporting = Reporting{
                Bugsnag:  BugsnagReporting{config.Reporting.Bugsnag.APIKey, config.Reporting.Bugsnag.ReleaseStage, config.Reporting.Bugsnag.Endpoint},
-               NewRelic: NewRelicReporting{config.Reporting.NewRelic.LicenseKey, config.Reporting.NewRelic.Name},
+               NewRelic: NewRelicReporting{config.Reporting.NewRelic.LicenseKey, config.Reporting.NewRelic.Name, config.Reporting.NewRelic.Verbose},
        }
 
        configCopy.Auth = Auth{config.Auth.Type(): Parameters{}}
```

**Comment by RichardScothern** [comment]
I added that change into a pull request here: https://github.com/docker/distribution/pull/360

**Pull request closed without merging**
