### PR TITLE
Formatting content digest calculation to avoid copyright symbols

### LINKED ISSUE #1197: copyright symbol in docs instead of literal characters
In the content digest section of the registry api, there are some copyright symbols. I'm not sure who's doing the interpretation/conversion.

screen shot 2015-11-20 at 14 30 51

https://github.com/docker/distribution/blame/master/docs/spec/api.md#L326
&
https://github.com/docker/distribution/blame/master/docs/spec/api.md#L328

I'm not sure how to test and fix or I would make a PR to do so.

### PR DESCRIPTION
**Pull request by MHBauer**
- resolves #1197

New look:
screen shot 2015-11-23 at 13 00 40

### CODE REVIEW

**Comment by moxiegirl** [comment]
@MHBauer Would you mind checking the 294-296 and putting that in code font too? It isn't coming through in the make docs properly.

Any change you make in the `api.md` the same changes should go in the `api.md.tmpl` file.

**Comment by MHBauer** [comment]
Yes, good to know about `.tmpl`.

**Comment by moxiegirl** [comment]
LGTM Thank you @MHBauer @RichardScothern

**Comment by RichardScothern** [comment]
LGTM

**Pull request merged**
