### PR TITLE
GCS: FileWriter.Size: return offset + buffer size for Writers that are not closed

### PR DESCRIPTION
**Pull request by aibaars**
@RichardScothern @manuelmazzuola

### CODE REVIEW

**Comment by RichardScothern** [comment]
@manuelmazzuola are you able to build a container to test with?  If not @aibaars could you do so and it's looking OK I'll make another release candidate 😿

**Comment by manuelmazzuola** [comment]
@RichardScothern Not today (GMT+1)
@aibaars If you can't I'll try it tomorrow

**Comment by aibaars** [comment]
@RichardScothern I built a container and pushed and pulled the debian and ubuntu images to/from it. This works fine. However, this also worked fine for me with the previous patch. 

Therefore, I would like to ask @manuelmazzuola to repeat his tests,just to be sure.

**Comment by manuelmazzuola** [comment]
@RichardScothern I've built, pushed and pulled different versions of the same image and seems to work fine.

**Comment by RichardScothern** [comment]
LGTM.

**Comment by aibaars** [comment]
@manuelmazzuola Many thanks!

**Comment by manuelmazzuola** [comment]
@aibaars Thanks to you

**Comment by RichardScothern** [comment]
@manuelmazzuola @aibaars thanks to both of you for helping with this 👍

**Comment by doanac** [comment]
This was merged in the 2.4 branch, but it was never merged into master so its broken in all subsequent releases.

**Pull request merged**
