### PR TITLE
Get rid of the goto statement in the Stat function of cachedBlobStatter

### PR DESCRIPTION
**Pull request by mssola**
Signed-off-by: Miquel Sabaté <msabate@suse.com>

### CODE REVIEW

**Comment by dmp42** [comment]
Hi @mssola 

I fail to see what this change is going to fix.

Can you elaborate a bit on the reasoning?

Thanks.

**Comment by stevvooe** [comment]
I don't see this addressing a specific bug. Closing for now. If it is addressing a problem, please re-open and we'll consider it.

**Comment by dmp42** [comment]
@mssola you are working on Portus, right?

**Comment by mssola** [comment]
@stevvooe you're right, this is not addressing a specific bug or issue, it's just a small cleanup. It's basically addressing the fact that this piece of code contained a `goto` statement that was easily avoidable.
@dmp42 yes, I'm working on Portus :)

**Comment by dmp42** [comment]
@mssola I guess debating whether goto is harmful or not is one of these eternal debate :-)

Portus: impressive work you are doing over there.

We are curious about your experience extending the registry like you did and would welcome your feedback.

**Comment by stevvooe** [comment]
@mssola What fears do you have about the use of the `goto` statement? Many of the concerns outlined in [Dijkstra's A Case against the GO TO Statement](https://www.cs.utexas.edu/users/EWD/ewd02xx/EWD215.PDF) have been addressed by the restrictions of the Go language. Check out [this explanation for an example](http://stackoverflow.com/questions/11064981/why-does-go-have-a-goto-statement).

In this case, we have clearly labeled sections of the code that delineate a cache lookup and fallback stanza. This both communicates behavior and intent. With the use of the `else` statement, one must cognitively the invert the condition of the `if` statement to `err == nil` and the infer the intent from comments or function documentation.

**Pull request closed without merging**
