### PR TITLE
Fix typo in comment of TestPOSTDownHandlerChangeStatus

### PR DESCRIPTION
**Pull request by yuchangchun1**

### CODE REVIEW

**Comment by stevvooe** [comment]
@yuchangchun1 Something looks wrong here. Isn't the `DownHandler` meant to make the handler return 503?

@NathanMcCauley Do these tests look right?

**Comment by NathanMcCauley** [comment]
DownHandler should return `200` when you tell it to down the service -- that is, you were successful in your request marking the service as down.

Follow-on requests to query the health will return 503.

**Comment by NathanMcCauley** [comment]
Basically, the test and code are correct afaict. I think we can close this PR and maybe open another one to clarify that comment better?

**Comment by stevvooe** [comment]
@NathanMcCauley Ah, I see. How to proceed is up to you.

LGTM

**Pull request closed without merging**
